---
title: "By Year - EPCs in V10"
author: "Boyana Buyuklieva"
date: "June, 2022"
output: html_document
---

#Incomplete

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
#library(DescTools)

library(dplyr)
library(tidyr)

#get folders
folders <- list.files(path = "../Data/all-domestic-certificates", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

folders <- folders[-342] #remove the .txt
```



##LODGEMENT_DATETIME = Date lodged on the Energy Performance of Buildings Register *col_character()*
##INSPECTION_DATE  = The date that the inspection was actually carried out by the energy assessor *col_date()* 


```{r loop}
dt_yearly <- list()
#1980 - 2022
i <- 0

for (LA in folders) {
  i <- i + 1
  ifelse( i %% 10 == 0, print(f), NA)
  
  certificates <- read_csv(paste0("../Data/all-domestic-certificates/",LA,"/certificates.csv"), 
    col_types = cols(COUNTY = col_character(), MAIN_HEATING_CONTROLS = col_character(),
        INSPECTION_DATE = col_date(format = "%Y-%m-%d"), 
        LMK_KEY = col_character(), LODGEMENT_DATE = col_date(format = "%Y-%m-%d"), 
        LODGEMENT_DATETIME = col_character()))
        #LODGEMENT_DATETIME = col_character() because it sometimes includes H:M:S

  for (year in unique()) {
    #https://stackoverflow.com/questions/58254425/how-to-add-a-row-to-data-frame-based-on-a-condition
  }
}

```



