---
title: "Duplicate (strings) EPCs in V10"
author: "Boyana Buyuklieva"
date: "May 20, 2022"
output: html_document
---

#This version is has linear time complexity. 

```{r setup, include=FALSE, echo = T}
knitr::opts_chunk$set(echo = TRUE)
library(readr)

start.time <- Sys.time()
ubdc_link <- read_csv("../Data/ubdc_link.csv", 
    col_types = cols(record = col_character(), 
        record1 = col_character()))
print(paste('load time:', Sys.time() - start.time)) #"load time: 3 mins"



start.time <- Sys.time()
ubdc_link <- ubdc_link[order(ubdc_link$ubdc_uprn),]  
print(paste('sort time:', Sys.time() - start.time)) #"sort time: 16.833909034729"
```


```{r path}
#get folders
folders <- list.files(path = "../Data/all-domestic-certificates", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

folders <- folders[-342] #remove the .txt
```


# Duplicate Defintion Testing
```{r loop}
str_dups <- data.frame()
uprn_dups <- data.frame()
udbc_UPRN <- data.frame()
folders_meta_dups <- data.frame()


counter = 0

start.time <- Sys.time()
for (LA in folders) {
  
  if( counter %% 20 == 0){print(LA)} 
  #CSV read
    certificates <- read_csv(paste0("../Data/all-domestic-certificates/",LA,"/certificates.csv"), 
    col_types = cols_only(
                          LMK_KEY = col_character(), 
                          INSPECTION_DATE = col_date(format = "%Y-%m-%d"),
                          LODGEMENT_DATE = col_date(format = "%Y-%m-%d"),
                          LODGEMENT_DATETIME = col_character(),
                          CURRENT_ENERGY_RATING = col_character(),
                          CURRENT_ENERGY_EFFICIENCY = col_character(),
                          ADDRESS = col_character(),
                          POSTCODE = col_character(),
                          UPRN = col_character(),
                          UPRN_SOURCE = col_character(),
                          LOCAL_AUTHORITY = col_character(),
                          LOCAL_AUTHORITY_LABEL = col_character(),
                          POSTTOWN = col_character(),
                          CONSTITUENCY_LABEL = col_character(),
                          TRANSACTION_TYPE = col_character(),
                          TENURE = col_character(),
                          COUNTY = '?') )
    
    certificates$folder <- LA #folder info
    row <- LA
      
  #Add the dups counts at folder level
  row <- cbind(row,length(certificates$LMK_KEY) )#denominator
  #Count empty UPRNs 
  row <- cbind(row,sum(is.na(certificates$UPRN)))  
  
    
  if(F){
  ###Dups df #######################################
  ##Baseline: by string match
  certificates$combined <- paste0(certificates$ADDRESS, certificates$POSTCODE) #measure of repeat entry here
  tmpdups <- certificates[duplicated(certificates$combined) | duplicated(certificates$combined, fromLast = TRUE),]
  tmpdups <- tmpdups[order(tmpdups$combined, tmpdups$INSPECTION_DATE),]
  str_dups <- rbind(str_dups,tmpdups)
  row <- cbind(row, length(tmpdups$LMK_KEY)) 
  
  
  #Based on UPRNs
  tmpdups1 <- certificates[duplicated(certificates$UPRN) | duplicated(certificates$UPRN, fromLast = TRUE),]
  uprn_dups <- rbind(uprn_dups,tmpdups1)
  

  row <- cbind(row, length(tmpdups1$LMK_KEY) ) 
    }
    
  #DIRECTIONS TO EXPLORE
  #certificates$udbc_UPRN <- ubdc_link$ubdc_uprn[bsearch(certificates$LMK_KEY, ubdc_link$lmk_key)]
  #binsearch / gtools
  #make ubdc_link$ubdc_uprn  a data.table , then setkey(data.table, key)  // touch by data.table[key]
  #test!
  #library(Dict)
  #ages <- Dict$new(ubdc_link$lmk_key,ubdc_link$ubdc_uprn)
  #Manual Based on V9 LUT:
  #start.time <- Sys.time()
  
  
  certificates$udbc_UPRN <- ubdc_link$ubdc_uprn[match(certificates$LMK_KEY, ubdc_link$lmk_key)]
  tmpdups2_2 <- certificates[duplicated(certificates$udbc_UPRN) | duplicated(certificates$udbc_UPRN, fromLast = TRUE),]
  udbc_UPRN <- rbind(udbc_UPRN,tmpdups2_2)
  #print(paste('time without unlist:', Sys.time() - start.time)) #"time without unlist: 3.05"
  row <- cbind(row, length(tmpdups2_2$LMK_KEY)) 
  
  folders_meta_dups <-rbind(folders_meta_dups, row)
  
  rm(tmpdups2_2,row)
  #rm(tmpdups,tmpdups1,tmpdups2_2,row)
  #gc()
  
  counter = counter + 1
}
print(paste('loop time:', Sys.time() - start.time))
#summary: UPRNS alone took 2h15 mins to complete. Creating dupsdf of 3.9GB 
#summary: UPRNS alone took 3h+  to complete. Creating dupsdf of 3.9GB 
#names(folders_meta_dups) <- c('folder', 'totalRows', 'NA_uprn', 'ubdc_link_uniq')
#write.csv(folders_meta_dups, '../Outputs/folders_meta_dups_ubdc_link_uniq.csv')
#save(udbc_UPRN, file = '../Data/WIP_udbc_UPRN.RData')

names(folders_meta_dups) <- c('folder', 'totalRows', 'NA_uprn','str_uniq', 'uprn_uniq', 'udbcUPRN_uniq')


```





# Feature Engineering Set-Up

```{r heavyload, cache=TRUE}
start.time <- Sys.time()


#loads str_dups [7 847 301]
#load(file = './MetaData&StringDups.RData')

#Df of all rows that repeat
tmp <- str_dups[,subsetCols ]
rm(str_dups)

##memory.size()
gc()#collect garbage 


#order by similarity & date
dupcol <- 'combined'
date <- 'INSPECTION_DATE'

tmp <- tmp[order(tmp[,dupcol],tmp[,date]),]
#create a faster key, based on the order
tmp$n_IDx <- seq(1,length(tmp$LMK_KEY),1)


print(paste('time to load:', Sys.time() - start.time))#9 mins
```

```{r define_engineered-features, cache=TRUE}
start.time <- Sys.time()


#flag first entries   
tmp$n_firstEntry <- F
firstEntry <-which(!duplicated(tmp$combined)) #3539058
tmp$n_firstEntry[firstEntry] <- T 
rm(firstEntry)

#set up the time column, relative to Inspection Date
tmp$n_deltaDays <-  0

#Delta(ER)
#might cause problems without trimming white spaces and caps
tmp$n_dER <- as.numeric(factor(tmp$CURRENT_ENERGY_RATING, 
                       ordered = T, levels = c('A','B','C','D','E','F','G')))
tmp$n_dEE <- tmp$CURRENT_ENERGY_EFFICIENCY


print(paste('runtime:', Sys.time() - start.time))#2 mins
```

```{r checks}
checks <- c("n_IDx","n_firstEntry","combined",
            "INSPECTION_DATE","n_deltaDays",
            "CURRENT_ENERGY_RATING","n_dER",
            "CURRENT_ENERGY_EFFICIENCY","n_dEE",
            "LMK_KEY","LOCAL_AUTHORITY")
```




#Simplified Version of Deltas

```{r solved_faster}

testingN <- length(tmp$combined)
# testingN <- 50000

start.time <- Sys.time()
tester <- head(tmp,testingN)


#vector giving  start of the repeats / group 
rangeStarts <- numeric(testingN)
for (row in tester$n_IDx) {
  
  if (tester$n_firstEntry[row] == T) {
    groupStart <- row
  }
  
  rangeStarts[row] <- groupStart
} 
print(paste('loop runtime:', Sys.time() - start.time)) # (.2 sec / 5k)  (20s / 8M)



start.time <- Sys.time()
tester$n_dER <- tester$n_dER[rangeStarts] - tester$n_dER # factor as numbers
tester$n_dEE <- tester$n_dEE - tester$n_dEE[rangeStarts]
tester$n_deltaDays <- as.numeric(difftime(tester$INSPECTION_DATE, tester$INSPECTION_DATE[rangeStarts], units = c("days"))) 
print(paste('operation runtime:', Sys.time() - start.time)) # (0.01 sec / 5k) (.5 / 8M)


print(paste('runtime:', Sys.time() - start.time)) # (approx 60s / 8 m)

#View(tester[,checks])

```



