---
title: "Feature_Engineering"
author: "Boyana Buyuklieva"
date: "May 19, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#options(scipen=0)
library(ggplot2)
```

## R Markdown

```{r cars, cache = TRUE}
load('./str_dups_deltas_c11.RData' )
checks <- c("n_firstEntry","combined",
            "INSPECTION_DATE","n_deltaDays",
            "CURRENT_ENERGY_RATING","n_dER",
            "CURRENT_ENERGY_EFFICIENCY","n_dEE",
            "LMK_KEY","LOCAL_AUTHORITY")

###Remove the first entries
repeat_dt <- str_dups_deltas_c11[str_dups_deltas_c11$n_firstEntry == F, ]
```

https://www.statmethods.net/graphs/density.html

```{r timeBetween}
#See how much time on average there is between the entries

sum(is.na(repeat_dt$n_deltaDays)) #6NAs
#View(repeat_dt[is.na(repeat_dt$n_deltaDays),])

mean(repeat_dt$n_deltaDays,na.rm = T) 
median(repeat_dt$n_deltaDays,na.rm = T)

#If the difference is very small, there might be an issue in counting the dups
Kd_deltaDays <- density(repeat_dt$n_deltaDays,na.rm = T) # returns the density data
plot(Kd_deltaDays) # plots the results
boxplot(repeat_dt$n_deltaDays)
```

```{r takes_ages}
week1 <- 7
approxMonth1 <- 30
approxyear1 <- 365
year5 <- 365*5
year10 <- 365*10

  
dt <- head(repeat_dt, 10000)
dt <- repeat_dt

deltaDays <- ggplot(dt, aes(x=n_deltaDays)) + 
  geom_density(fill="grey", alpha = 0.7)

deltaDays+ 
  geom_vline(aes(xintercept=week1),color="red", linetype="dashed", size=1)+ 
  geom_vline(aes(xintercept=approxMonth1),color="blue", linetype="dashed", size=1)+ 
  geom_vline(aes(xintercept=approxyear1),color="black", linetype="solid", size=0.7)+ 
  geom_vline(aes(xintercept=year5),color="black", linetype="solid", size=0.7)+ 
  geom_vline(aes(xintercept=year10),color="black", linetype="solid", size=0.7)+ 
  theme_classic()+
  ggtitle(label = "Days since first entry was recorded",
              subtitle = "n = 4.3M, based on inspection date")
```

```{r}
sum(repeat_dt$n_deltaDays<7, na.rm = T) #244034
sum(repeat_dt$n_deltaDays>5000, na.rm = T) #133
sum(repeat_dt$n_deltaDays>365*15, na.rm = T) #49
```







```{r rankChanges}
#What is the most common ER rank change?

###Check where values are negative
neg <- 



###Check for NAs

###Check and remove 0 changes 

###Make a historgram of the rank changes (-5,)
```


```{r}
#Are small improvements happening?

###Check and remove 0 changes 


```


