---
title: "P4_Cramer's V"
author: "Bonnie Buyuklieva"
date: "2022-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rcompanion)
library(data.table)
library(ggplot2)


#https://www.statology.org/cramers-v-in-r/
#https://www.statology.org/chi-square-test-of-independence-in-r/



source("../Outputs/Thesis_custom_scripts.R", local = knitr::knit_global())
data <- loadRData( "../Data/RData_crossSectional/_NS_dt_N14m377170.RData")

#data <- loadRData( "../Data/RData_crossSectional/_combi_SC_dt_big_crossSect_EPCs_cleaned_N16m984358.RData")
data[ , EXTENSION_COUNT:= as.numeric(EXTENSION_COUNT), ]

fct <- c("Victorian and earlier (pre 1900s)","Edwardian (1900-1929)","Near WW2 (1930-1949)","Post WW2","Modern (66-96s)","Modern (66-96s)","Modern (66-96s)","New (Pre 2007)","New (Pre 2007)","New(Pre 2007)","Very New (Post 2007)","unknown")
levels(data$ssimp_nn_construction_age_band) <- fct
data[,ssimp_nn_construction_age_band := factor(ssimp_nn_construction_age_band, levels = unique(fct), ordered = T)]

```




```{r meta_data_table}
cols <- names(data) # colnames
cols_na <- sapply(data, function(x) sum(is.na(x)))

#count of unique factors
l_unique_factors <- sapply(data, function(x) length(unique(x)))
test1 <- as.data.frame(l_unique_factors)
test <- as.data.frame(do.call(cbind, test1))
type <- sapply(data , function(x) typeof(x)) 

cols <- cbind(names = names(data), 
              type = type,
              nas_counts = cols_na, 
              factors = test)
#write.csv(cols, './testMEdel.csv')

```

```{r choose factors}
#get cols with 3-37 factprs

interest_factors_cols <- cols[cols$l_unique_factors < 38 & cols$l_unique_factors > 2, 'names']

#remove some
interest_factors_cols <- setdiff(interest_factors_cols, c("CURRENT_ENERGY_RATING", "n_CEErel","n_CEIrel",
                                                          "CONSTRUCTION_AGE_BAND",# harmonised
                                                          "TENURE", # harmonised
                                                          "TRANSACTION_TYPE",# harmonised 
                                                          "GLAZED_TYPE"#GLAZED_TYPE needs harmonising
                                                          ))
```


#for tomorrow: harmonise more from raw.
#interact 
- tenure with age
- tenure age and property type
- tenure age and 


```{r CramerV_tenure}
measure = 'n_CEErel'
panelsheet <- data.frame()
output2 <- data.frame()

#Cramer V
for (col in interest_factors_cols) {
  #DROPPING C - LIKELY TO GIVE HIGHER CORRELATION, easier to plot
  #make Paneldata
  tmp_data <- data[ n_CEErel != 'C' ,  .(n = .N), by = c(col, measure) ]
  tmp_panelsheet <- tmp_data
  tmp_panelsheet$topic <- col
  names(tmp_panelsheet) <- c('subgroup', 'mobility','year','n', 'topic')
  panelsheet <- rbind(panelsheet, tmp_panelsheet)
  
  #Minus one drops the category names
  tmp_data <- data[ n_CEErel != 'C' ,  .(n = .N), by = c(col, measure) ]
  tmp_data <- dcast(tmp_data, paste(col, "~", measure), value.var = 'n')
  tmp_cramer_var <- cramerV(as.matrix( tmp_data[,-1] ))
  tmp_chi_var <- chisq.test( tmp_data[,-1] )
  
  
  tmp_chi <- tmp_chi_var$statistic
  tmp_chi_param <- tmp_chi_var$parameter
  tmp_chi_method <- tmp_chi_var$method

  row <- cbind(measure, col, 
        tmp_cramer_var,
        tmp_chi,tmp_chi_param,tmp_chi_method)
  
  output2 <- rbind.data.frame(output2,row)
}

write.csv( output2 , file = '../Outputs/N14m377170_CramerV_CEErel_2x35_vars.csv')
write.csv( panelsheet , file = '../Outputs/N14m377170_panelsheet_CEErel_2x35.csv')
```




```{r CramerV_tenure}
measure = 'n_CEErel'
panelsheet <- data.frame()
output2 <- data.frame()

#Cramer V
for (col in interest_factors_cols) {
  #DROPPING C - LIKELY TO GIVE HIGHER CORRELATION, easier to plot
  #make Paneldata
  tmp_data <- data[ n_CEErel != 'C' ,  .(n = .N), by = c(col, measure, 'n_tenure') ]
  tmp_panelsheet <- tmp_data
  tmp_panelsheet$topic <- col
  names(tmp_panelsheet) <- c('subgroup', 'mobility','year','n', 'topic')
  panelsheet <- rbind(panelsheet, tmp_panelsheet)
  
  #Minus one drops the category names
  tmp_data <- data[ n_CEErel != 'C' ,  .(n = .N), by = c(col, measure) ]
  tmp_data <- dcast(tmp_data, paste(col, "~", measure), value.var = 'n')
  tmp_cramer_var <- cramerV(as.matrix( tmp_data[,-1] ))
  tmp_chi_var <- chisq.test( tmp_data[,-1] )
  
  
  tmp_chi <- tmp_chi_var$statistic
  tmp_chi_param <- tmp_chi_var$parameter
  tmp_chi_method <- tmp_chi_var$method

  row <- cbind(measure, col, 
        tmp_cramer_var,
        tmp_chi,tmp_chi_param,tmp_chi_method)
  
  output2 <- rbind.data.frame(output2,row)
}

write.csv( output2 , file = '../Outputs/N14m377170_CramerV_CEErel_tenure.csv')
write.csv( panelsheet , file = '../Outputs/N14m377170_panelsheet_CEErel_tenure.csv')
```


```{r CramerV_ssimp_nn_construction_age_band}
measure = 'n_CEErel'
panelsheet <- data.frame()
output2 <- data.frame()

#Cramer V
for (col in interest_factors_cols) {
  #DROPPING C - LIKELY TO GIVE HIGHER CORRELATION, easier to plot
  #make Paneldata
  tmp_data <- data[ n_CEErel != 'C' ,  .(n = .N), by = c(col, measure, 'ssimp_nn_construction_age_band') ]
  tmp_panelsheet <- tmp_data
  tmp_panelsheet$topic <- col
  names(tmp_panelsheet) <- c('subgroup', 'mobility','year','n', 'topic')
  panelsheet <- rbind(panelsheet, tmp_panelsheet)
  
  #Minus one drops the category names
  tmp_data <- data[ n_CEErel != 'C' ,  .(n = .N), by = c(col, measure) ]
  tmp_data <- dcast(tmp_data, paste(col, "~", measure), value.var = 'n')
  tmp_cramer_var <- cramerV(as.matrix( tmp_data[,-1] ))
  tmp_chi_var <- chisq.test( tmp_data[,-1] )
  
  
  tmp_chi <- tmp_chi_var$statistic
  tmp_chi_param <- tmp_chi_var$parameter
  tmp_chi_method <- tmp_chi_var$method

  row <- cbind(measure, col, 
        tmp_cramer_var,
        tmp_chi,tmp_chi_param,tmp_chi_method)
  
  output2 <- rbind.data.frame(output2,row)
}

write.csv( output2 , file = '../Outputs/N14m377170_CramerV_CEErel_ssimp_nn_construction_age_band.csv')
write.csv( panelsheet , file = '../Outputs/N14m377170_panelsheet_CEErel_ssimp_nn_construction_age_band.csv')
```




```{r CramerV_tenure}
measure = 'n_CEErel'
panelsheet <- data.frame()
output2 <- data.frame()

#Cramer V
for (col in interest_factors_cols) {
  #DROPPING C - LIKELY TO GIVE HIGHER CORRELATION, easier to plot
  #make Paneldata
  tmp_data <- data[ n_CEErel != 'C' ,  .(n = .N), by = c(col, measure, 'age') ]
  tmp_panelsheet <- tmp_data
  tmp_panelsheet$topic <- col
  names(tmp_panelsheet) <- c('subgroup', 'mobility','year','n', 'topic')
  panelsheet <- rbind(panelsheet, tmp_panelsheet)
  
  #Minus one drops the category names
  tmp_data <- data[ n_CEErel != 'C' ,  .(n = .N), by = c(col, measure) ]
  tmp_data <- dcast(tmp_data, paste(col, "~", measure), value.var = 'n')
  tmp_cramer_var <- cramerV(as.matrix( tmp_data[,-1] ))
  tmp_chi_var <- chisq.test( tmp_data[,-1] )
  
  
  tmp_chi <- tmp_chi_var$statistic
  tmp_chi_param <- tmp_chi_var$parameter
  tmp_chi_method <- tmp_chi_var$method

  row <- cbind(measure, col, 
        tmp_cramer_var,
        tmp_chi,tmp_chi_param,tmp_chi_method)
  
  output2 <- rbind.data.frame(output2,row)
}

write.csv( output2 , file = '../Outputs/N14m377170_CramerV_CEErel_age.csv')
write.csv( panelsheet , file = '../Outputs/N14m377170_panelsheet_CEErel_age.csv')
```












```{r}
for (topic_plot in groups) {

  
  topic_plot = 'b_LND'
  topic_plot = col
  
  tmp_dt <- subset(panelsheet, topic == topic_plot)
  tmp_dt <- droplevels(tmp_dt)
  tmp_dt$subgroup_Formal <- ordered(tmp_dt$subgroup_Formal,
                                    levels = unique(tmp_dt$subgroup_Formal[order(tmp_dt$Factor)]) )
  #using data, lable with formal name and rotate label as specified
  p <- custom_mosaic(tmp_dt, tmp_dt$Formal)
  
  if(T){
    #get the numeric meta data of the ggmosaic
  temp <- ggplot_build(p)$data[[1]]
  plot(p)+
  geom_label(data = temp,               
             aes(x = round((xmin + xmax)/2,3), 
             y = 0, 
             label = c('',round(temp$.wt[2],3),'',round(temp$.wt[4],3))) )
  #borough order:
  count <- as.data.frame(cbind(label = temp$label,yval = round(temp$ymax,3), xval = round(temp$xmax,3) ) )
  count <- subset(count, count$yval != 1)
  order <- rev(unique(temp$x1__subgroup_Formal[order(temp$ymax)]))
  }
  
  
  plot(p)
  
  ggsave(file=paste0("./_tall_mosaics/_",topic_plot,"_mosaic.png"), width = 210, height = 230, units = "mm")
}
```

