---
title: "P4_Cramer's V"
author: "Bonnie Buyuklieva"
date: "2022-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rcompanion)
library(data.table)
library(ggplot2)

#https://www.statology.org/cramers-v-in-r/
#https://www.statology.org/chi-square-test-of-independence-in-r/



source("../Outputs/Thesis_custom_scripts.R", local = knitr::knit_global())
data <- loadRData( "../Data/RData_crossSectional/_NS_dt_N14m377170.RData")

#data <- loadRData( "../Data/RData_crossSectional/_combi_SC_dt_big_crossSect_EPCs_cleaned_N16m984358.RData")
data[ , EXTENSION_COUNT:= as.numeric(EXTENSION_COUNT), ]

```




```{r meta_data_table}
cols <- names(data) # colnames
cols_na <- sapply(data, function(x) sum(is.na(x)))

#count of unique factors
l_unique_factors <- sapply(data, function(x) length(unique(x)))
test1 <- as.data.frame(l_unique_factors)
test <- as.data.frame(do.call(cbind, test1))
type <- sapply(data , function(x) typeof(x)) 

cols <- cbind(names = names(data), 
              type = type,
              nas_counts = cols_na, 
              factors = test)
#write.csv(cols, './testMEdel.csv')

```

```{r choose factors}
#get cols with 3-37 factprs

interest_factors_cols <- cols[cols$l_unique_factors < 38 & cols$l_unique_factors > 2, 'names']

#remove some
interest_factors_cols <- setdiff(interest_factors_cols, c("CURRENT_ENERGY_RATING", "n_CEErel","n_CEIrel",
                                                          "CONSTRUCTION_AGE_BAND",# harmonised
                                                          "TENURE", # harmonised
                                                          "TRANSACTION_TYPE",# harmonised 
                                                          "GLAZED_TYPE"#GLAZED_TYPE needs harmonising
                                                          ))
```


#for tomorrow: harmonise more from raw.
#interact 
- tenure with age
- tenure age and property type
- tenure age and 

```{r CramerV}
measure = 'n_CEErel'
panelsheet <- data.frame()


#Cramer V
for (col in interest_factors_cols) {
  #DROPPING C - LIKELY TO GIVE HIGHER CORRELATION, easier to plot
  tmp_data <- data[ n_CEErel != 'C' ,  .(n = .N), by = c(col, measure) ]
  #make Paneldata
  tmp_panelsheet <- tmp_data
  tmp_panelsheet$topic <- col
  names(tmp_panelsheet) <- c('subgroup', 'mobility','n', 'topic')
  panelsheet <- rbind(panelsheet, tmp_panelsheet)
  
  #Minus one drops the category names
  tmp_data <- dcast(tmp_data, paste(col, "~", measure), value.var = 'n')
  tmp_cramer_var <- cramerV(as.matrix( tmp_data[,-1] ))
  tmp_chi_var <- chisq.test( tmp_data[,-1] )
  
  
  tmp_chi <- tmp_chi_var$statistic
  tmp_chi_param <- tmp_chi_var$parameter
  tmp_chi_method <- tmp_chi_var$method

  row <- cbind(measure, col, 
        tmp_cramer_var,
        tmp_chi,tmp_chi_param,tmp_chi_method)
  
  output2 <- rbind.data.frame(output2,row)
}

write.csv( output2 , file = '../Outputs/N14m377170_CramerV_CEErel_2x35_vars.csv')
write.csv( panelsheet , file = '../Outputs/N14m377170_panelsheet_CEErel_2x35.csv')
```



```{r}
panelsheet <- data.frame()

for (col in interest_factors_cols) {
  tmp_data <- data[ ,  .(n = .N), by = c(col, measure) ]
  
  tmp_panelsheet <- tmp_data
  tmp_panelsheet$topic <- col
  names(tmp_panelsheet) <- c('subgroup', 'mobility','n', 'topic')
  panelsheet <- rbind(panelsheet, tmp_panelsheet)
  

}
```


```{r}
plot <- output2[order(output2$tmp_cramer_var, decreasing = T),]



head(plot)
plot <- plot[ plot$tmp_cramer_var > 0.1 ,]

ggplot(plot, aes(x=seq_along(tmp_cramer_var), tmp_cramer_var,))+
  geom_point(aes( size = col))
```


```{r}
+
  #geom_text_repel(aes(label=col), colour = "black", size = 3,nudge_x = 0.5,segment.color = NA)+
  #scale_colour_manual(values=named)+
  scale_y_continuous( breaks =seq(0,0.24, by = .02), 
                      labels = seq(0,0.24, by = .02) , name = "Cramer's V")+
  scale_x_continuous( breaks = seq(1,11, by = 1), 
                      labels = seq(1,11, by = 1), 
                      name = "Ranked Strength of Association")+
    geom_hline(yintercept=.1, linetype="dashed",size=.1, colour ='gray')+
  theme_classic()
```






```{r 3wayCramer}
output <- data.frame(matrix(nrow = 0, ncol = 6))
  
#Cramer V
for (col in interest_factors_cols) {
  tmp_data <- data[ ,  .(n = .N), by = c(col, measure) ]
  tmp_data <- dcast(tmp_data, paste(col, "~", measure), value.var = 'n')
  
  #Minus one drops the category names
  tmp_cramer_var <- cramerV(as.matrix( tmp_data[,-1] ))
  tmp_chi_var <- chisq.test( tmp_data[,-1] )
  
  
  tmp_chi <- tmp_chi_var$statistic
  tmp_chi_param <- tmp_chi_var$parameter
  tmp_chi_method <- tmp_chi_var$method

  row <- cbind(measure, col, 
        tmp_cramer_var,
        tmp_chi,tmp_chi_param,tmp_chi_method)
  
  output <- rbind.data.frame(output,row)
}

write.csv( output, file = '../Outputs/N14m377170_CramerV_CEErel_3x28_vars.csv')


output2 <- data.frame(matrix(nrow = 0, ncol = 6))

```














# COR
```{r get_unique_per_column}
#threashold of factors I care about
#get cols with 3-37 factprs

interest_factors_cols <- cols[cols$l_unique_factors < 38 & cols$l_unique_factors > 3, 'names']

#remove some
interest_factors_cols <- setdiff(interest_factors_cols, c("CURRENT_ENERGY_RATING",
                                                          "CONSTRUCTION_AGE_BAND",# harmonised
                                                          "TENURE", # harmonised
                                                          "TRANSACTION_TYPE",# harmonised 
                                                          "GLAZED_TYPE"#GLAZED_TYPE needs harmonising
                                                          ))
for (col in interest_factors_cols) {
  print(paste( col, is.factor(data[ , col ,with = F])) )
}



unique <- data.frame()
for (col in interest_factors_cols) {
    row = paste(unique(data[ , col ,with = F]))
    print(row)
    row <-  gsub("[c(]", "",row)
    row <-  gsub("[)]", "", row)
    row <- cbind( col, row)
    unique <- rbind(unique,row)
}






unique <- data.frame()
for (col in interest_factors_cols) {
  if( is.factor(data[ , col ,with = F]) ){
    row = unique(as.character(data[ , col ,with = F])) 
    # row = as.factor(x)
    #row = paste(levels(data[ , col ,with = F]))
  }else{
    row = paste(unique(data[ , col ,with = F]))
  } 
    print(row)
    unique <- rbind(unique,row)
}




cols <- cbind(names = names(data), 
              type = type,
              nas_counts = cols_na, 
              factors = test,
              unique = unique)


test <- c("nn_builtForm","n_propTyp")
test1 <- data[, test ,with = FALSE]
unique_factors <- sapply(test1, function(x) ifelse(is.factor(x), levels(x), unique(x)) )

```

```{r}
#http://www.sthda.com/english/wiki/correlation-test-between-two-variables-in-r
#group | subgroup | method () | cor (estimate)| p (p.value)

start.time <- Sys.time()
corr <- cor.test(data$CURRENT_ENERGY_EFFICIENCY, data$ENVIRONMENT_IMPACT_CURRENT,  method="pearson")

cor_estimate <-  corr$estimate

  
Sys.time() - start.time


```

```{r}
start.time <- Sys.time()
cor.test(data$CURRENT_ENERGY_EFFICIENCY, data$ENVIRONMENT_IMPACT_CURRENT,  method="spearman")
#https://rpubs.com/aaronsc32/spearman-rank-correlation
Sys.time() - start.time
```



# CHI
## Sample
```{r}
#n_Crel / n_CEErel / nn_CEIrel / n_CEIrel
#Long to Table
sub_data <- data[, .(n = .N) ,by=c('x_simp_nn_builtFormXn_propTyp','n_CEErel') ]
sub_data <- dcast(sub_data, x_simp_nn_builtFormXn_propTyp ~ n_CEErel, value.var = 'n'  )
row.names(sub_data) <- c(sub_data[,1])

#Minus one drops the category names
cramerV(as.matrix(sub_data[,-1]))#0.2098 

#VERSION DROPPING C - LIKELY TO GIVE HIGHER CORRELATION
sub_data1 <- data[ n_CEErel != 'C', .(n = .N) ,by=c('x_simp_nn_builtFormXn_propTyp','n_CEErel') ]
sub_data1 <- dcast(sub_data1, x_simp_nn_builtFormXn_propTyp ~ n_CEErel, value.var = 'n'  )
#Minus one drops the category names
cramerV(as.matrix(sub_data1[,-1]))#0.2456 
```



```{r compareToExpected}
##Compare Chi to Some theoretical
sub_data3 <- data[ n_imd_grp != 'M.Deprived.1-3', .(n = .N) ,by=c('x_simp_nn_builtFormXn_propTyp','n_CEErel') ]
sub_data3 <- dcast(sub_data3, x_simp_nn_builtFormXn_propTyp ~ n_CEErel, value.var = 'n'  )
chisq.test(sub_data3[,-1] , p = sub_data[,-1])
```





