---
title: "P3_CrossSectional_EDA"
author: "Boyana Buyuklieva"
date: "August 30, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache.lazy = FALSE)
library(dplyr)
library(tidyverse)
library(data.table)
library(readr)
library(foreign)
library(ggExtra)
library(gridExtra)


loadRData <- function(fileName){
    #loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}

big_Dt_CSsubset_N6M7 <- loadRData("../Outputs/WIP_crossSectional/ONSUD_crossSectional_subset_N16744771.RData")
fctr_levels <- c("C+","C","C-")
big_Dt_CSsubset_N6M7[,n_Crel := factor(n_Crel, levels = fctr_levels, ordered = T)]

#tally <- big_Dt_CSsubset_N6M7[, .(n = .N) ,by=NUMBER_HABITABLE_ROOMS ]
big_Dt_CSsubset_N6M7[, NUMBER_HABITABLE_ROOMS:=as.integer(NUMBER_HABITABLE_ROOMS)]

fctr_levels <- c(paste0(seq(1,6,1), 'HR'), '+7HR' )
big_Dt_CSsubset_N6M7[ , n_habitable_rooms_grp := ifelse( NUMBER_HABITABLE_ROOMS>6,'+7HR', paste0(NUMBER_HABITABLE_ROOMS,'HR'))]
big_Dt_CSsubset_N6M7[,n_habitable_rooms_grp := factor(n_habitable_rooms_grp, levels = fctr_levels, ordered = T)]



big_Dt_CSsubset_N6M7[, n_CURRENT_ENERGY_EFFICIENCY := ifelse( CURRENT_ENERGY_EFFICIENCY>100 ,101, CURRENT_ENERGY_EFFICIENCY)]
big_Dt_CSsubset_N6M7[, n_POTENTIAL_ENERGY_EFFICIENCY := ifelse( POTENTIAL_ENERGY_EFFICIENCY>100 ,101, POTENTIAL_ENERGY_EFFICIENCY)]

big_Dt_CSsubset_N6M7[, n_ENVIRONMENT_IMPACT_CURRENT := ifelse( ENVIRONMENT_IMPACT_CURRENT>100 ,101, ENVIRONMENT_IMPACT_CURRENT)]
big_Dt_CSsubset_N6M7[, n_ENVIRONMENT_IMPACT_POTENTIAL := ifelse( ENVIRONMENT_IMPACT_POTENTIAL>100 ,101, ENVIRONMENT_IMPACT_POTENTIAL)]


big_Dt_CSsubset_N6M7[, n_potEE := n_POTENTIAL_ENERGY_EFFICIENCY - n_CURRENT_ENERGY_EFFICIENCY]
big_Dt_CSsubset_N6M7[, n_potIE := n_ENVIRONMENT_IMPACT_POTENTIAL - n_ENVIRONMENT_IMPACT_CURRENT]

#formatting:
lettermapping <-  data.frame( letter = c('A','B','C','D','E','F','G'), 
                              cutoff = c(92, 81, 69, 55, 39, 21, 0))

```


###IMD:
```{r attached_IMDs}
#multiple deprivation EW
IMD19<- read.dbf("../Data/_shapefiles/Lower_Super_Output_Area_(LSOA)_IMD_2019__(OSGB1936)/Lower_Super_Output_Area_(LSOA)_IMD_2019__(OSGB1936).dbf")

#income deprivation E
income_imd2019lsoa_E <- fread("../Data/imd2019lsoa/imd2019lsoa.csv",
                     drop="Units", #empty column anyway
                     colClasses = c( "FeatureCode" = "character",
                                     "Measurement" = "character",
                                     "Value" = "numeric",
                                     "Indices of Deprivation" = "character"))

#Measurements are: "Rank"   "Decile" "Score"
#income_imd2019lsoa_E <- setNames(income_imd2019lsoa_E, c("lsoa11cd","Date","Measurement","Value","Indices of Deprivation") )
setnames(income_imd2019lsoa_E, c("FeatureCode"), c("lsoa11cd"))

EDA_cols <- read_csv("../Data/EDA_colour_scheme.csv")
#EDA_cols <- subset(EDA_cols[EDA_cols$geography_name %in%  cross_data, ])

#formatting:
lettermapping <-  data.frame( letter = c('A','B','C','D','E','F','G'), 
                              cutoff = c(92, 81, 69, 55, 39, 21, 0))

#Add IMD
big_Dt_CSsubset_N6M7[IMD19,  on = 'lsoa11cd', c('n_IMDRank','n_IMDDecil') := .(IMDRank,IMDDecil)]

#Add IoD
##can select other IoD here
imd_bincome <-  income_imd2019lsoa_E[ `Indices of Deprivation` == "b. Income Deprivation Domain",]
imd_bincome <-dcast(imd_bincome, lsoa11cd ~ Measurement, value.var = c("Value"))
big_Dt_CSsubset_N6M7[imd_bincome,  on = 'lsoa11cd', c('n_bIoDRank_income','n_bIoDDecil_income') := .(Rank,Decile)]


big_Dt_CSsubset_N6M7[ , n_bIoDDecil_income_grp := cut(n_bIoDDecil_income,
                            breaks = c(0, 3, 7, Inf),
                            include.lowest= TRUE, labels=c('n_bIoD_1-3','n_bIoD_4-7','n_bIoD_8-10')) ]
```



```{r CEE addingInTenure BF}
cols <- c('TOTAL_FLOOR_AREA','NUMBER_HEATED_ROOMS','NUMBER_HABITABLE_ROOMS',
          'n_habitable_rooms_grp','n_CURRENT_ENERGY_EFFICIENCY','n_ENVIRONMENT_IMPACT_CURRENT',
          'n_builtForm','PROPERTY_TYPE','n_tenure','n_bIoDDecil_income_grp', 'n_Crel','CO2_EMISS_CURR_PER_FLOOR_AREA')

big_Dt_CSsubset_N6M7 <- big_Dt_CSsubset_N6M7[!is.na(TOTAL_FLOOR_AREA),]
vis_subset_N16M7 <- big_Dt_CSsubset_N6M7[ ,..cols]

```



```{r C02 per floor area 95th }
#Check CO2 emissions per floor area , by tenure and deprivation 

subset_P95 <- vis_subset_N16M7[!is.na(CO2_EMISS_CURR_PER_FLOOR_AREA)& 
CO2_EMISS_CURR_PER_FLOOR_AREA <= quantile(vis_subset_N16M7$TOTAL_FLOOR_AREA, 0.95, na.rm = T) & 
CO2_EMISS_CURR_PER_FLOOR_AREA >= quantile(vis_subset_N16M7$TOTAL_FLOOR_AREA, 0.05, na.rm = T)
,]

ggplot(subset_P95, aes(x = CO2_EMISS_CURR_PER_FLOOR_AREA, colour = n_habitable_rooms_grp)) +
    #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
    stat_density(lwd = 1, linetype = 1, position="identity",geom="line", bw = 2)+
    geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.3)+
    geom_vline( xintercept =  c(69,81), colour = 'black', size=.3)+
    #annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
    theme_minimal()+
    theme(legend.position = 'bottom', legend.box = 'horizontal')+
    scale_colour_viridis_d(option = "plasma", direction	= -1)+ 
    scale_x_continuous( breaks= lettermapping$cutoff)+
    facet_grid(rows = vars(n_tenure))
```



```{r}
ggplot(subset_P95[!is.na(n_bIoDDecil_income_grp),], aes(x = CO2_EMISS_CURR_PER_FLOOR_AREA, colour = n_tenure)) +
    #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
    stat_density(lwd = 1, linetype = 1, position="identity",geom="line", bw = 2)+
    geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.3)+
    geom_vline( xintercept =  c(69,81), colour = 'black', size=.3)+
    #annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
    theme_minimal()+
    theme(legend.position = 'bottom', legend.box = 'horizontal')+
    scale_colour_viridis_d(option = "plasma", direction = -1)+
    scale_x_continuous( breaks= lettermapping$cutoff)+
    facet_grid(rows = vars(n_Crel), vars(n_bIoDDecil_income_grp)  )
```


```{r}
ggplot(subset_P95[!is.na(n_bIoDDecil_income_grp),], aes(x = CO2_EMISS_CURR_PER_FLOOR_AREA, colour = n_habitable_rooms_grp)) +
    #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
    stat_density(lwd = 1, linetype = 1, position="identity",geom="line", bw = 2)+
    geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.3)+
    geom_vline( xintercept =  c(69,81), colour = 'black', size=.3)+
    #annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
    theme_minimal()+
    theme(legend.position = 'bottom', legend.box = 'horizontal')+
    scale_colour_viridis_d(option = "plasma", direction	= -1)+ 
    scale_x_continuous( breaks= lettermapping$cutoff)+
    facet_grid(rows = vars(n_Crel), vars(n_bIoDDecil_income_grp))
```





