---
title: "Tenure - EPCs in V10"
author: "Boyana Buyuklieva"
date: "May 4, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("data.table")
library("xlsx")

loadRData <- function(fileName){
    #loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}

```



```{r path}
#get folders
folders <- list.files(path = "../Data/all-domestic-certificates", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

folders <- folders[-342] #remove the .txt
```

#Counting on CSV Directory
```{r LUT_making}
entries_to_factors <- function(column_to_extract_factors_from = 'TENURE') {

LUT<- list()
start.time <- Sys.time()

for (LA in folders) {
  
  #print(LA)
  certificates <- fread(paste0("../Data/all-domestic-certificates/",LA,"/certificates.csv"),
                        colClasses = 'character',
                        select = column_to_extract_factors_from)

  LUT[[LA]] <- unique(certificates[,get(column_to_extract_factors_from)])
  
}
#shows which factor is in which folder
folder_to_factor <- as.data.frame(unlist(LUT))
LUT<- as.data.frame(unique(folder_to_factor$`unlist(LUT)`))
colnames(LUT) <- paste0( column_to_extract_factors_from, 'factors')

print(paste('loop time:', Sys.time() - start.time))

return(LUT)
}


LUT_built_form <- entries_to_factors(column_to_extract_factors_from = "BUILT_FORM")
LUT_property_type <- entries_to_factors(column_to_extract_factors_from = "PROPERTY_TYPE")
LUT_age_band <- entries_to_factors(column_to_extract_factors_from = "CONSTRUCTION_AGE_BAND")

LUT_transaction <- entries_to_factors(column_to_extract_factors_from = "TRANSACTION_TYPE")

#note: I am not doing tallys here because repeat entries will skew the picture

if(F){
  write.xlsx(LUT_built_form,
             file = "../Data/OS-N_EPC_v10_LUT+dictionaries.xlsx", sheetName="BUILT_FORM", append=TRUE)  
  
  write.xlsx(LUT_property_type,
             file = "../Data/OS-N_EPC_v10_LUT+dictionaries.xlsx", sheetName="PROPERTY_TYPE", append=TRUE) 
  
  write.xlsx(LUT_age_band,
             file = "../Data/OS-N_EPC_v10_LUT+dictionaries.xlsx", sheetName="CONSTRUCTION_AGE_BAND", append=TRUE)
  
  write.xlsx(LUT_transaction,
             file = "../Data/OS-N_EPC_v10_LUT+dictionaries.xlsx", sheetName="TRANSACTION_TYPE", append=TRUE)
}
```


```{r rowCounting_V10_complete}
rowCount<- c('LA','rows')
for (LA in folders) {
  
  #print(LA)
  certificates <- fread(paste0("../Data/all-domestic-certificates/",LA,"/certificates.csv"),
                        select = "LMK_KEY",
                        colClasses = 'character')

  rowCount <- rbind(rowCount, t(c(LA,lengths(certificates))) )
  
}

if(F){
   write.xlsx(rowCount,
             file = "../Data/OS-N_EPC_v10_LUT+dictionaries.xlsx", sheetName="RawRowTotals", append=TRUE)
}
```


#Counting on RData Directory


```{r long}
#get folders
long_data <- list.files(path = "../Data/RData_longitudinal", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

LUT_transaction <- read_excel("../Data/OS-N_EPC_v10_LUT+dictionaries.xlsx", sheet = "TRANSACTION_TYPE",range = cell_cols("B:B"))

metadata_long <- setNames(data.table(matrix(nrow = 0, ncol = lengths(LUT_transaction)+8)), 
                          c('region','LA','n_row','unique_GRPs' ,'unique_n_UPRN', 'na_n_UPRN', 'na_UPRN', 'GRPrepeat_more_than2x',c(LUT_transaction$TRANSACTION_TYPEfactors)))
print_counter = 0

start.time <- Sys.time()

#long_data <- long_data[1] #testing
for (region in long_data) {
  tmp_region_dt <- loadRData(paste0("../Data/RData_longitudinal/",region) )
  print(region)
  
  #for(LA in unique(tmp_region_dt[, LAD11NM])[1:5] ){#testing
  for(LA in unique(tmp_region_dt[, LAD11NM]) ){  
    
      print_counter = print_counter+1
      if(print_counter %% 20 == 0){print(LA)} 
    
    tmp_dt_subset <- tmp_region_dt[LAD11NM == LA,]
    tmp_dt_subset[, n_appearance := .N , by=list(n_GRP)]
    
    
    n_row <- lengths(tmp_dt_subset)[1]
    unique_GRPs <- length(unique(tmp_dt_subset$n_GRP))
    unique_n_UPRN <- length(unique(tmp_dt_subset$n_UPRN))
    na_n_UPRN <- sum(is.na(tmp_dt_subset$n_UPRN))
    na_UPRN <- sum(is.na(tmp_dt_subset$UPRN))
    
    #groups!
    repeat_more_than2x <- lengths(tmp_dt_subset[ n_appearance > 2, .N , by=list(n_GRP)])[1]
    
    #cleanUp the region
    region <- gsub(".*_", "", region)
    region <- gsub(".RData", "", region)
    
    #add transaction tally 
    transactionDt <- tmp_dt_subset[, .N, by=.(TRANSACTION_TYPE)]
    #compains here. ? use.names=FALSE
    trans <- transactionDt$N[match(LUT_transaction$TRANSACTION_TYPEfactors,transactionDt$TRANSACTION_TYPE, use.names=FALSE)]
    
    
    row <- c(region, LA, n_row, unique_GRPs, unique_n_UPRN, na_n_UPRN,na_UPRN,repeat_more_than2x, trans)
    
    metadata_long <- rbindlist(list(metadata_long, as.list(row)) )
    rm(tmp_dt_subset)
    
  }
}

write.xlsx(metadata_long,
             file = "../Data/OS-N_EPC_v10_LUT+dictionaries.xlsx", sheetName="meta_data_long", append=TRUE)

print(paste('runtime:', Sys.time() - start.time))#
```




