---
title: "Duplicate (strings) EPCs in V10"
author: "Boyana Buyuklieva"
date: "May 4, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(DescTools)
```



```{r path}
#get folders
folders <- list.files(path = "../Data/all-domestic-certificates", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

folders <- folders[-342] #remove the .txt
```


```{r folders_meta_vars}
#Get difference by LAD, eg.g: 
folders_meta <- data.frame(names = folders)
folders_meta$name <- folders
folders_meta$totalEntries <- 0
folders_meta$PerCentOneOffEntries <- 0 ## % one-off entries by folder.

## Min, Max, Mean, SD of INSPECTION DATE and/or Lodgementdate
folders_meta$IdateMin <- 0
folders_meta$IdateMax <- 0
folders_meta$IdateMedian <- 0
  
folders_meta$LdateMin <- 0
folders_meta$LdateMax <- 0
folders_meta$LdateMedian <- 0


## CURRENT_ENERGY_RATING (factor)
folders_meta$cERmedian <- 0


## POTENTIAL - CURRENT_ENERGY_EFFICIENCY (int)
folders_meta$p_cEEficMedian <- 0
folders_meta$p_cEEficMean <- 0
folders_meta$p_cEEficSD <- 0

##ADDD\1
##percent rental 
## percent rental that are B-D, Percent rental under D

## Other ideas
######or (ENVIROMENT_IMPACT_CURRENT - POTENTIAL)
######or any other more specific: e.g. C02 emission, lighting, heating, hotwater,
## Proportion of PROPERTY_TYPE and/or BUILT_FORM and/or Transaction_Type and/or CONSTRUCTION_AGE_BAND and/or TENURE.Note: inconsistent factors
```

```{r loop}
str_dups <- data.frame()

for (f in folders) {
  LA <- f
  certificates <- read_csv(paste0("../Data/all-domestic-certificates/",LA,"/certificates.csv"))
  
  #Dups df #######################################
  certificates$combined <- paste0(certificates$ADDRESS, certificates$POSTCODE) #measure of repeat entry here
  tmpdups <- certificates[duplicated(certificates$combined) | duplicated(certificates$combined, fromLast = TRUE),]
  tmpdups$folder <- LA #folder info
  tmpdups <- tmpdups[order(tmpdups$combined, tmpdups$INSPECTION_DATE),]
  str_dups <- rbind(str_dups,tmpdups)
  
  
  
  #Folders Meta df #######################################
  #Get difference by LAD, eg.g:
  folders_meta[folders_meta$name == LA,]$totalEntries <- length(certificates$LMK_KEY)
  folders_meta[folders_meta$name == LA,]$PerCentOneOffEntries <- 1 - length(tmpdups$LMK_KEY)/length(certificates$LMK_KEY) ## % one-off entries by folder.
  
  ## Min, Max, Mean, SD of INSPECTION DATE and/or Lodgementdate
  folders_meta[folders_meta$name == LA,]$IdateMin <- min(Year(certificates$INSPECTION_DATE))
  folders_meta[folders_meta$name == LA,]$IdateMax <- max(Year(certificates$INSPECTION_DATE))
  folders_meta[folders_meta$name == LA,]$IdateMedian <- median(Year(certificates$INSPECTION_DATE))

  
  folders_meta[folders_meta$name == LA,]$LdateMin <- min(Year(certificates$LODGEMENT_DATETIME))
  folders_meta[folders_meta$name == LA,]$LdateMax <- max(Year(certificates$LODGEMENT_DATETIME))
  folders_meta[folders_meta$name == LA,]$LdateMedian <- median(Year(certificates$LODGEMENT_DATETIME))
  
  ## CURRENT_ENERGY_RATING (factor)
  certificates$CURRENT_ENERGY_RATING <- as.numeric(factor(certificates$CURRENT_ENERGY_RATING, 
                       ordered = T, levels = c('A','B','C','D','E','F','G')))
  folders_meta[folders_meta$name == LA,]$cERmedian <- median(certificates$CURRENT_ENERGY_RATING)
  
  
  ## POTENTIAL - CURRENT_ENERGY_EFFICIENCY (int)
  folders_meta[folders_meta$name == LA,]$p_cEEficMedian <- median(certificates$POTENTIAL_ENERGY_EFFICIENCY - certificates$CURRENT_ENERGY_EFFICIENCY)
  folders_meta[folders_meta$name == LA,]$p_cEEficMean <- mean(certificates$POTENTIAL_ENERGY_EFFICIENCY - certificates$CURRENT_ENERGY_EFFICIENCY)
  folders_meta[folders_meta$name == LA,]$p_cEEficSD <- sd(certificates$POTENTIAL_ENERGY_EFFICIENCY - certificates$CURRENT_ENERGY_EFFICIENCY)
  
}

#note: 2269 parsing failures.4241 parsing failures.3219 parsing failures.4639 parsing failures.
#South-Ribble 3286 parsing failures.
```





```{r}
#get dups
LA <- folders[2]
certificates <- read_csv(paste0("../Data/all-domestic-certificates/",LA,"/certificates.csv"))

certificates$combined <- paste0(certificates$ADDRESS, certificates$POSTCODE)


tmpdups <- certificates[duplicated(certificates$combined) | duplicated(certificates$combined, fromLast = TRUE),]
tmpdups$folder <- LA

str_dups <- rbind(str_dups,tmpdups)
str_dups <- str_dups[order(str_dups$combined, str_dups$INSPECTION_DATE),]
```


[Information on how the Energy Rating map to Energy Efficiency](https://www.edfenergy.com/energy-efficiency/how-improve-your-epc-rating)


```{r}
#detecting an improvement
## this can be based on the 'CURRENT_ENERGY_RATING': "E" "B" "C" "D" "F" "G" "A"
## or 'CURRENT_ENERGY_EFFICIENCY'
#### NOTES: 'POTENTIAL_ENERGY_RATING','POTENTIAL_ENERGY_EFFICIENCY'

c <- c('combined','INSPECTION_DATE','firstEntry','n_delta')

tmp <- head(str_dups,25)


#get the first entry
firstEntry <-which(!duplicated(tmp$combined))
tmp$firstEntry <- F
tmp$firstEntry[firstEntry] <- T

}