---
title: "P3_Longitudinal_BigDt"
author: "Bonnie Buyuklieva"
date: "2022-09-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#add the ONS Geographies - over time? 
#Load loop to create big_Dt
```


```{r to do for longitudinal subset}
#resolve age band:
big_Dt <- big_Dt[, nn_construction_age_band := n_construction_age_band]
big_Dt <- big_Dt[n_construction_age_band == '2012 onwards' | n_construction_age_band =='2007-2011', nn_construction_age_band := '2007 onwards']
big_Dt <- big_Dt[n_construction_age_band == 'Not applicable', nn_construction_age_band := 'unknown']
fctr_levels <- c("Pre-1900","1900-1929","1930-1949","1950-1966","1967-1975","1976-1982","1983-1990","1991-1995","1996-2002","2003-2006","2007 onwards","unknown")
big_Dt[,nn_construction_age_band := factor(nn_construction_age_band, levels = fctr_levels, ordered = T)]

#control outliers in CEE
big_Dt[,nn_CURRENT_ENERGY_EFFICIENCY := CURRENT_ENERGY_EFFICIENCY]
big_Dt[CURRENT_ENERGY_EFFICIENCY > 101, nn_CURRENT_ENERGY_EFFICIENCY := NA]

#refactor:
fct_propertyType <- c('Park home','Maisonette','Bungalow','Flat','House')
big_Dt[,PROPERTY_TYPE := factor(PROPERTY_TYPE, levels = rev(fct_propertyType), ordered = T)]

fct_n_builtForm <- c('Semi-Detached','Mid-Terrace','Detached','End-Terrace','unknown')
big_Dt[,n_builtForm := factor(n_builtForm, levels = fct_n_builtForm, ordered = T)]

fct_n_tenure <- c('owner-occupied','rental (private)','rental (social)','unknown')
big_Dt[,n_tenure := factor(n_tenure, levels = fct_n_tenure, ordered = T)]
```