---
title: "P6_CS_NS_full_Figs"
author: "Bonnie Buyuklieva"
date: "2022-09-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
SeeRawData = F
```

#Use with _NS_subset
( to do: combine BigDt with NS_subset)

```{r makingdata_smaller}
cols <- c('TOTAL_FLOOR_AREA','NUMBER_HEATED_ROOMS','NUMBER_HABITABLE_ROOMS',
          'n_habitable_rooms_grp','n_CURRENT_ENERGY_EFFICIENCY','n_ENVIRONMENT_IMPACT_CURRENT',
          'n_builtForm','PROPERTY_TYPE','n_tenure','n_bIoDDecil_income_grp', 'n_Crel','CO2_EMISS_CURR_PER_FLOOR_AREA')

full_sample = lengths(NS_dt_N16m3)[1]
```



The figure below shows how property types are spread across building types. Terrace houses are most common, as are terrace flats. Maisonettes are flats across two floors. 

*Explain  how a detached maisonette is different from a house.*
*Explain  a semi-detached bungalow.*
```{r Fig2_Pt1_historgram}
plot_dt <- NS_dt_N16m3[ , by = c('nn_builtForm', 'PROPERTY_TYPE'),  .(n = .N)]
#plot_dt$percent <-  plot_dt$n/ sum(plot_dt$n)
plot_dt$nK <- plot_dt$n/1000
  
ggplot(plot_dt, aes(x= nn_builtForm, y=nK))+
  geom_bar(stat='identity')+
  scale_y_continuous(labels = format(seq(0,4800, by = 250), big.mark = ' '),
                     breaks = seq(0,4800, by = 250))+
  facet_grid(PROPERTY_TYPE ~ .) +
  coord_flip()+
  labs( x = '', y = 'Number of properties in 1 000s', )+
  theme(axis.text.y=element_text(angle=30,hjust=1)) +
  theme_minimal()+
  labs(title = "", subtitle = paste0("Subset n=", full_sample) )
```


```{r Fig2_Pt1_historgram_by_age_band}
plot_dt <- NS_dt_N16m3[ , by = c('nn_builtForm', 'PROPERTY_TYPE','nn_construction_age_band'),  .(n = .N)]

  
ggplot(NS_dt_N16m3, aes(x= nn_construction_age_band, y=stat(count), fill = nn_construction_age_band))+
  geom_bar()+
  #scale_y_continuous(labels = format(seq(12,12000, by = 1000), big.mark = ' '),
  #                  breaks = seq(1200,1200000, by = 10000))+
  facet_grid(nn_builtForm ~ PROPERTY_TYPE, scale = "free_y") +
  #coord_flip()+
  labs( x = 'Building Age', y = 'Number of properties in 100s' )+
  theme_minimal()+
  theme(axis.text.y = element_text(hjust = 1, size=6),
        axis.text.x = element_text(angle = 90, hjust = 1, size=7),
        legend.position="none")+
  labs(title = "", subtitle = paste0("Subset n=", full_sample) )
```



```{r Fig2_Pt2}
#facetgrid: tenure x property type, region
  ggplot(NS_dt_N16m3, aes(x = nn_CURRENT_ENERGY_EFFICIENCY, colour = nn_construction_age_band )) +
  #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
  stat_density(lwd = 1, linetype = 1, position="identity",geom="line", bw = 2)+
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.3)+
  geom_vline( xintercept =  c(69,81), colour = 'black', size=.3)+
  #annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_x_continuous(name = 'Current Energy Efficiency' , breaks= lettermapping$cutoff)+
  facet_grid(rows = vars(nn_builtForm),vars(PROPERTY_TYPE))+
  labs(title = "", subtitle = paste0("Subset n=", full_sample) )
```


```{r Fig3_CEE_EIC_scatter}


if(SeeRawData){
# See raw data
  raw <- ggplot(NS_dt_N16m3, aes(CURRENT_ENERGY_EFFICIENCY, ENVIRONMENT_IMPACT_CURRENT))+
  geom_point()+ #geom_point(aes(color = n_Crel))
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')
  
ggMarginal(raw, type="density") 
}


edited <- ggplot(NS_dt_N16m3, aes(n_CURRENT_ENERGY_EFFICIENCY, n_ENVIRONMENT_IMPACT_CURRENT))+
 geom_point(aes(color = nn_letter_Diff_CEE_EIC, alpha = 0.05)) +
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_x_continuous( breaks= lettermapping$cutoff)+
  scale_y_continuous( breaks= lettermapping$cutoff)+
  scale_colour_grey()+ 
  annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  labs(title = "", subtitle = paste0("Subset n=", full_sample) )

ggMarginal(edited, type="density")
```


#Bonus:

```{r habitable_to_heated_rooms}
subset_n <- lengths(NS_dt_N16m3[!is.na(NUMBER_HEATED_ROOMS) & !is.na(NUMBER_HABITABLE_ROOMS),])[1]
subset_n <- format(subset_n, big.mark = ' ', trim = T)


p <- ggplot(NS_dt_N16m3[!is.na(NUMBER_HEATED_ROOMS) & !is.na(NUMBER_HABITABLE_ROOMS),],
            aes(NUMBER_HEATED_ROOMS, NUMBER_HABITABLE_ROOMS, fill = nn_letter_Diff_CEE_EIC)) + 
 geom_point(aes(color = nn_letter_Diff_CEE_EIC, alpha = 0.05))+
  labs(caption = paste('N (non-empty) = ', subset_n)) + 
  theme_minimal()+ theme(legend.position = 'bottom')+
  labs(title = "", subtitle = paste0("Subset n=", full_sample) )

ggMarginal(p, type = "histogram")  
```


```{r heatedrooms}
##For heated rooms groups: slee
#Denisty of floorspace by heated rooms, box plot 
#Check EPCs, by tenure and deprivation, group by number of rooms

  ggplot(NS_dt_N16m3[!is.na(n_heated_rooms_grp),], aes(x = n_ENVIRONMENT_IMPACT_CURRENT, colour = n_heated_rooms_grp)) +
  #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
  stat_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.6)+ 
  annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  #theme_classic() +
  theme_minimal()+
  scale_colour_viridis_d(option = "plasma", direction	= -1)+ 
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_x_continuous(name = 'Current Environmental Impact' , breaks= lettermapping$cutoff)+
  labs(title = "", subtitle = paste0("Subset n=", full_sample) )
```

