---
title: "P5_Descriptives"
author: "Bonnie Buyuklieva"
date: "2022-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
library(data.table)
library(ggplot2)
library(readr)
library(lme4)
library(jtools)


source("../Outputs/Thesis_custom_scripts.R", local = knitr::knit_global())
data <- loadRData( "../Data/RData_crossSectional/_NS_dt_N14m377170.RData")
#dataCS <- loadRData( "../Data/RData_crossSectional/_combi_SC_dt_big_crossSect_EPCs_cleaned_N16m984358.RData")





```



# Key variables:
```{r , echo=FALSE}
plotdata <- data[ ,  .(n = .N), by = c('nnn_construction_age_band12') ]
ggplot(plotdata, aes(x=nnn_construction_age_band12, y = n)) + 
 geom_bar(stat="identity")+ theme_minimal()+coord_flip()

#11 age groups
ggplot(data=data[ ,.SD[sample(.N,300)] ], aes(x=nnn_construction_age_band12, y=CURRENT_ENERGY_EFFICIENCY)) +
  geom_boxplot()+ theme_minimal()+coord_flip()







plotdata <- data[ ,  .(n = .N), by = c('nnn_construction_age_band10') ]
ggplot(plotdata, aes(x=nnn_construction_age_band10, y = n)) + 
 geom_bar(stat="identity")+ theme_minimal()+coord_flip()

plotdata <- data[ ,  .(n = .N), by = c('nnn_construction_age_band9') ]
ggplot(plotdata, aes(x=nnn_construction_age_band9, y = n)) + 
 geom_bar(stat="identity")+ theme_minimal()+coord_flip()





#10 age groups
ggplot(data=data[ ,.SD[sample(.N,300)] ], aes(x=nnn_construction_age_band10, y=CURRENT_ENERGY_EFFICIENCY)) +
  geom_boxplot()+ theme_minimal()+coord_flip()

plotdata <- data[ ,  .(n = .N), by = c('nnn_construction_age_band12') ]
ggplot(plotdata, aes(x=nnn_construction_age_band9, y = n)) + 
 geom_bar(stat="identity")+ theme_minimal()+coord_flip()

#9 age groups
ggplot(data=data[ ,.SD[sample(.N,300)] ], aes(x=nnn_construction_age_band9, y=CURRENT_ENERGY_EFFICIENCY)) +
  geom_boxplot()+ theme_minimal()+coord_flip()
```

```{r}
plotdata <- data[ ,  .(n = .N), by = c('x_simp_nn_builtFormXn_propTyp') ]
ggplot(data=plotdata, aes(x=x_simp_nn_builtFormXn_propTyp, y=n)) +
  geom_bar(stat="identity")+ theme_minimal()+coord_flip()

#5 morpho groups
ggplot(data=data[ ,.SD[sample(.N,300)] ], aes(x=x_simp_nn_builtFormXn_propTyp, y=CURRENT_ENERGY_EFFICIENCY)) +
  geom_boxplot()+ theme_minimal()+coord_flip()


#Hard to intepret
#ggplot(data=data[ ,.SD[sample(.N,300)] ], aes(x=x_nn_builtFormXn_propTyp, y=CURRENT_ENERGY_EFFICIENCY)) +
#  geom_boxplot()+ theme_minimal()+coord_flip()

```






```{r M0_emptyModel}
start.t <- Sys.time()
m0 <- lm(formula = CURRENT_ENERGY_EFFICIENCY ~ NULL, data = data)
#m0 <- lmer(formula = CURRENT_ENERGY_EFFICIENCY ~ 1, data = data)
#No random effects terms specified in formula
Sys.time() - start.t

m0 
#plot intercept on histogram
```

```{r M0_histogram, echo=FALSE}
#Separate code on change
# It is currently a requirement for rental properties to achieve at least a rating of ‘E’, which is reflected in the sharp rise in properties at the bottom of this grade rated at 39 points (from 2025 onwards this will rise to band ‘C’, which is also reflected). 



#All EPCS histo
lettermapping <-  data.frame( letter = c('A','B','C','D','E','F','G'), 
                              cutoff = c(92, 81, 69, 55, 39, 21, 0))

ggplot() + geom_histogram(data = data[RGN11NM == 'London'], 
                              aes(CURRENT_ENERGY_EFFICIENCY , alpha=0.9 ),
                              binwidth = 1)+
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.6)+ 
  annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  #theme_classic() +
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_x_continuous(name = 'Current Energy Efficiency' , breaks= lettermapping$cutoff)+
  #scale_y_continuous(name = 'Count of EPCs' ,breaks=seq(0,100000,10000))+
  theme(legend.position="none")+
  labs(title = '                                              empty model (mean)',
         tag = paste0("N = ", format(lengths(data)[1], big.mark=" ", trim=TRUE)) ) +
  geom_vline(xintercept = m0$coefficients, colour = 'red', size = 1) 
```

```{r minvalue_bump}
#make into separate script
ones <- data[ CURRENT_ENERGY_EFFICIENCY == 1, ]
print(paste('Percent CEE = 1:' , round(lengths(zeros)[1]/lengths(data)[1]*100,2), '. Which is n = ', lengths(zeros)[1], 'rows' ))


cols <-  c("SAP_version","RGN11NM","n_habitable_rooms_grp","n_tenure","nnn_construction_age_band12","x_simp_nn_builtFormXn_propTyp",'TRANSACTION_TYPE')

for (col in cols) {
#plotdata <-  setnames(ones[ ,  .(n = .N), by = c('nnn_construction_age_band12') ],  c('n','x'))

plotdata <-  setnames(ones[ ,  .(n = .N), by = c(col) ],  c('y','n'))
 p <- ggplot(aes( x = n, y = y), data = plotdata)+
 geom_bar(stat="identity")+ theme_minimal()#+coord_flip() 
 print(p)
}

# /*
#   Most EPCs values lie between 1 (lowest) - 100 (highest, with net energy exporting homes being able to score higher) (Crawley et al. 2019, p2). Our data includes 0.16% (n =23k properties) with the lowest rating. These tend to be marketed sales properties built pre-1900 with some ‘newer’ ones from up to the 1980s. 
# */
```



# Baseline Regressions

```{r}
a_output <- tidyr::expand_grid(
  #Age = unique(data$nnn_construction_age_band12),
  Morphology = unique(data$x_simp_nn_builtFormXn_propTyp),
  Tenure = unique(data$n_tenure)
)



#1.76
plotdata <- data[,.(n = .N), by = c('n_tenure')]
plotdata$nP <- round(plotdata$n/sum(plotdata$n) *100 ,2)
```





Ordered vs unorderd factor: [R's default is to fit a series of polynomial functions or contrasts to the levels of the variable. The first is linear (.L), the second is quadratic (.Q), the third is cubic (.C), and so on](https://stackoverflow.com/questions/57297771/interpretation-of-l-q-c-4-for-logistic-regression)

M1 as ordered: 
```{r M1_age_PTBF_vars_2_ordered , echo=FALSE, results='hide'}
#x_simp_nn_builtFormXn_propTyp[5]
#nnn_construction_age_band12[12]

start.t <- Sys.time()
m1 <- lm( formula = CURRENT_ENERGY_EFFICIENCY ~ nnn_construction_age_band12 + x_simp_nn_builtFormXn_propTyp, data = data)
Sys.time() - start.t #< 1min

summ(m1)
```

```{r , echo=FALSE}
summary(m1)
```


#Unordered:
M1, unordered: 

## 2 Variable
```{r M1_age_PTBF_vars_2, echo=FALSE, results='hide'}
#x_simp_nn_builtFormXn_propTyp[5]
#nnn_construction_age_band12[12]
fit <- data[ , .(CURRENT_ENERGY_EFFICIENCY, nnn_construction_age_band12 = factor( nnn_construction_age_band12 , ordered = FALSE ), 
                 x_simp_nn_builtFormXn_propTyp = factor( x_simp_nn_builtFormXn_propTyp , ordered = FALSE )) ]

start.t <- Sys.time()
m1 <- lm( formula = CURRENT_ENERGY_EFFICIENCY ~ nnn_construction_age_band12 + x_simp_nn_builtFormXn_propTyp, data = fit)
Sys.time() - start.t #< 1min

summ(m1)
```

```{r , echo=FALSE}
summary(m1)
```

## 4 Variable

```{r M2_age_PTBF__SAP_climate_date_vars_4}
fit <- data[ , .(CURRENT_ENERGY_EFFICIENCY, 
                 nnn_construction_age_band12 = factor( nnn_construction_age_band12 , ordered = FALSE ), 
                 x_simp_nn_builtFormXn_propTyp = factor( x_simp_nn_builtFormXn_propTyp , ordered = FALSE ),
                 SAP_version = factor( SAP_version , ordered = FALSE ),
                 SAP_climate_grp = factor( SAP_climate_grp , ordered = FALSE) ) ]


start.t <- Sys.time()
m2 <- lm( formula = CURRENT_ENERGY_EFFICIENCY ~ nnn_construction_age_band12 + x_simp_nn_builtFormXn_propTyp + SAP_version + SAP_climate_grp , data = fit)
Sys.time() - start.t
```

```{r , echo=FALSE}
summary(m2)
```

## 5 Variable

```{r M2_age_PTBF__SAP_climate_date__LAD_vars_5}
fit <- data[ , .(CURRENT_ENERGY_EFFICIENCY, 
                 nnn_construction_age_band12 = factor( nnn_construction_age_band12 , ordered = FALSE ), 
                 x_simp_nn_builtFormXn_propTyp = factor( x_simp_nn_builtFormXn_propTyp , ordered = FALSE ),
                 SAP_version, SAP_climate_grp,
                 LAD11NM) ]


start.t <- Sys.time()
m3 <- lm( formula = CURRENT_ENERGY_EFFICIENCY ~ nnn_construction_age_band12 + x_simp_nn_builtFormXn_propTyp + SAP_version + SAP_climate_grp + LAD11NM, data = fit)
Sys.time() - start.t
```

```{r , echo=FALSE}
summary(m3)
```



# Unordered factors, by Tenure
```{r}
fit <- data[ , .(CURRENT_ENERGY_EFFICIENCY, 
                 nnn_construction_age_band12 = factor( nnn_construction_age_band12 , ordered = FALSE ), 
                 x_simp_nn_builtFormXn_propTyp = factor( x_simp_nn_builtFormXn_propTyp , ordered = FALSE ), SAP_version, SAP_climate_grp, LAD11NM, n_tenure) ]


start.t <- Sys.time()
m2 <- lm( formula = CURRENT_ENERGY_EFFICIENCY ~ nnn_construction_age_band12 + x_simp_nn_builtFormXn_propTyp + SAP_version + SAP_climate_grp + LAD11NM, data = fit[ n_tenure ==  "rental (social)",])
Sys.time() - start.t


```

```{r, echo=FALSE}

try(plot_summs(m1, m2))

```








