---
title: "NS_P5_ANOVA"
author: "Bonnie Buyuklieva"
date: "2022-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r anova_p1_1min}

#https://www.linkedin.com/learning/r-essential-training-part-2-modeling-data/comparing-means-with-multiple-categorical-predictors-factorial-analysis-of-variance?autoplay=true&u=69919578
start.t <- Sys.time()
#ssimp_nn_construction_age_band [9 levels]
#n_propTyp [4 levels, 3 used]

fit <- aov( data = data, CURRENT_ENERGY_EFFICIENCY ~ ssimp_nn_construction_age_band + n_propTyp +  ssimp_nn_construction_age_band*n_propTyp)

Sys.time()- start.t

```


```{r anova_p2}
summary(fit)
```

```{r anova_p3}
start.t <- Sys.time()
model.tables(fit)
Sys.time()- start.t
```


```{r anova_p4}
TukeyHSD_95 <- TukeyHSD(fit, conf.level=.95)
TukeyHSD_99 <- TukeyHSD(fit, conf.level=.99)
```


```{r}
#most conservation: https://www.statology.org/pairwise-comparison-in-r/
scheffe_95 <- DescTools::ScheffeTest(fit, conf.level = 0.95)
scheffe_99 <- DescTools::ScheffeTest(fit, conf.level = 0.99)
```

