---
title: "P5_Descriptives"
author: "Bonnie Buyuklieva"
date: "2022-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(ggplot2)

source("../Outputs/Thesis_custom_scripts.R", local = knitr::knit_global())
data <- loadRData( "../Data/RData_crossSectional/_NS_dt_N14m377170.RData")

#dataCS <- loadRData( "../Data/RData_crossSectional/_combi_SC_dt_big_crossSect_EPCs_cleaned_N16m984358.RData")
```


```{r anomalies}
anomalies_cols <- c("LMK_KEY", "n_UPRN", "RGN11NM", "LAD11NM","LOCAL_AUTHORITY","LOCAL_AUTHORITY_LABEL",
                    "str_concat","POSTCODE",
                    "nn_CEI_rating","CURRENT_ENERGY_RATING",
                    "MAIN_FUEL", "MAINHEAT_DESCRIPTION", "NUMBER_HABITABLE_ROOMS",
                    "n_propTyp","nn_builtForm", "ssimp_nn_construction_age_band",
                    "n_tenure","n_transactTyp"  )

# D above : 55
# D below : 54
t1_anomalies <-  data[ENVIRONMENT_IMPACT_CURRENT > 54 & CURRENT_ENERGY_EFFICIENCY < 55, anomalies_cols , with = F] # 112 077, in the smaller subset
t2_anomalies <-  data[ENVIRONMENT_IMPACT_CURRENT < 55 &  CURRENT_ENERGY_EFFICIENCY > 54, anomalies_cols , with = F] # 2 038 886, smaller 

#discrepancies_CEE-CEI
write.csv(t1_anomalies, file = '../Outputs/discrepancies_CEE-CEI/t1_anomalies_LessC02.csv')
write.csv(t2_anomalies, file = '../Outputs/discrepancies_CEE-CEI/t2_anomalies_BetterRunning.csv')

#covert to factor: RGN11NM, nn_builtForm, n_transactTyp 


skimr::skim(t2_anomalies)
#tally
a_tally <- data[ ,  .(n = .N), by = c('n_tenure') ]


a_tally <- data[ ,  .(n = .N), by = c('x_nn_builtFormXn_propTyp') ]
```




```{r boxplots_raw}
ggplot(
       data, 
       #data[CURRENT_ENERGY_EFFICIENCY< minthreshold & CURRENT_ENERGY_EFFICIENCY> maxthreshold], 
       aes(x=CURRENT_ENERGY_EFFICIENCY, 
                 y=ssimp_nn_construction_age_band, fill=n_propTyp)) + 
    geom_boxplot() +
    facet_wrap(~n_tenure, scale="free")
```


```{r histogram}
#All EPCS histo
lettermapping <-  data.frame( letter = c('A','B','C','D','E','F','G'), 
                              cutoff = c(92, 81, 69, 55, 39, 21, 0))

ggplot() + geom_histogram(data = data[RGN11NM == 'London'], 
                              aes(CURRENT_ENERGY_EFFICIENCY , alpha=0.9 ),
                              binwidth = 1)+
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.6)+ 
  annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  #theme_classic() +
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_x_continuous(name = 'Current Energy Efficiency' , breaks= lettermapping$cutoff)+
  #scale_y_continuous(name = 'Count of EPCs' ,breaks=seq(0,100000,10000))+
  theme(legend.position="none")+
  labs(title = 'Current Energy Efficiency - subset checks',
         tag = paste0("N = ", format(lengths(data)[1], big.mark=" ", trim=TRUE)) ) 
```

##control for age, n_propTyp and then n_tenure. 

```{r barplots}
#Age bands Histo
options(scipen = 999)
ggplot(data) + geom_bar(aes(y = nn_construction_age_band))+
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  #scale_x_continuous(name = 'Count of EPCs' ,breaks=seq(0,500000,2500000))+
  theme(legend.position="none")+
  labs(title = 'Age Bands',
         tag = paste0("N = ", format(lengths(data)[1], big.mark=" ", trim=TRUE)) ) 



ggplot(data) + geom_bar(aes(y = ssimp_nn_construction_age_band))+
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  #scale_x_continuous(name = 'Count of EPCs' ,breaks=seq(0,500000,2500000))+
  theme(legend.position="none")+
  labs(title = 'Age Bands',
         tag = paste0("N = ", format(lengths(data)[1], big.mark=" ", trim=TRUE)) ) 
```



```{r histogram_big}
#All EPCS histo
lettermapping <-  data.frame( letter = c('A','B','C','D','E','F','G'), 
                              cutoff = c(92, 81, 69, 55, 39, 21, 0))

ggplot() + geom_histogram(data = data, 
                              aes(CURRENT_ENERGY_EFFICIENCY , alpha=0.9 ),
                              binwidth = 1)+
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.6)+ 
  annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  #theme_classic() +
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_x_continuous(name = 'Current Energy Efficiency' , breaks= lettermapping$cutoff)+
  #scale_y_continuous(name = 'Count of EPCs' ,breaks=seq(0,100000,10000))+
  theme(legend.position="none")+
  labs(title = 'Current Energy Efficiency in England and Wales',
         tag = paste0("N = ", format(lengths(data)[1], big.mark=" ", trim=TRUE)) ) 

```





```{r 2_way_Age_Property_Type}
library('svglite')

#slide_Age_Property_Type <-  
  
  
  ggplot(dat = data, 
       aes(x= ssimp_nn_construction_age_band, y=stat(count), fill = ssimp_nn_construction_age_band))+
  geom_bar()+
  facet_grid(n_CEE_binary ~ n_propTyp, scale = "free_y") +
  #coord_flip()+
  labs( x = 'Building Age and Property Type', y = 'Number of properties' )+
  theme_minimal()+
  theme(axis.text.y = element_text(hjust = 1, size=6),
        axis.text.x = element_text(angle = 25, hjust = 1, size=7),
        legend.position="none")+
  labs(subtitle = paste0("n=", format(lengths(data)[1], big.mark = ' ') ) ) +
  labs(title = "Building Characteristics of Cross-sectional EPC Records", caption ='Author: Bonnie Buyuklieva, @Bonnie_0000 \n Project: OS Narrate, UCL 2022-23 \nCentre for Advanced Spatial Analysis ')

#ggsave(file="./slide_Age_Property_Type.svg", plot=slide_Age_Property_Type, width=15, height=8)
#slide_Age_Property_Type
```


```{r 3_way_Age_Property_Type_Tenure}
#p <- 
  
ggplot(dat = data[ n_CEE_binary == "C & C+" & n_tenure != 'unknown' ], 
       aes(x= ssimp_nn_construction_age_band, y=stat(count), fill = ssimp_nn_construction_age_band))+
  geom_bar()+
  facet_grid(n_tenure ~ n_propTyp, scale = "free_y") +
  #coord_flip()+
  labs( x = 'Building Age and Property Type', y = 'Number of properties' )+
  theme_minimal()+
  theme(axis.text.y = element_text(hjust = 1, size=6),
        axis.text.x = element_text(angle = 45, hjust = 1, size=7),
        legend.position="none")+
  labs(subtitle = paste0("n=", format(lengths(data[ n_CEE_binary == "C & C+" ])[1], big.mark = ' ') ) ) +
  labs(title = "Building Characteristics of Cross-sectional EPC Records, C and Above", caption ='Author: Bonnie Buyuklieva, @Bonnie_0000 \n Project: OS Narrate, UCL 2022-23 \nCentre for Advanced Spatial Analysis ')


#ggsave(file="./Age_Property_Type_Tenure_CC+.svg", plot=p, width=14, height=14)
```



```{r imd}
deprivs <- c('n_bIoDDecil_income','n_gIoDDecil_barriers',)




measure = 'n_CEE_binary'
panelsheet <- data.frame()
output2 <- data.frame()

#Cramer V
for (col in deprivs) {
  #DROPPING C - LIKELY TO GIVE HIGHER CORRELATION, easier to plot
  #make Paneldata
  tmp_data <- NS_dt[  ,  .(n = .N), by = c(col, measure) ]
  tmp_panelsheet <- tmp_data
  tmp_panelsheet$topic <- col
  names(tmp_panelsheet) <- c('subgroup', 'mobility','year','n', 'topic')
  panelsheet <- rbind(panelsheet, tmp_panelsheet)
  
  
  
  cor(measure, col,  method = "pearson", use = "complete.obs")
  
  #Minus one drops the category names
  tmp_data <- data[ n_CEErel != 'C' ,  .(n = .N), by = c(col, measure) ]
  tmp_data <- dcast(tmp_data, paste(col, "~", measure), value.var = 'n')
  
  
  tmp_cramer_var <- cramerV(as.matrix( tmp_data[,-1] ))
  tmp_chi_var <- chisq.test( tmp_data[,-1] )
  
  
  
  #SPEARMAN HERE:
  tmp_chi <- tmp_chi_var$statistic
  tmp_chi_param <- tmp_chi_var$parameter
  tmp_chi_method <- tmp_chi_var$method

  row <- cbind(measure, col, 
        tmp_cramer_var,
        tmp_chi,tmp_chi_param,tmp_chi_method)
  
  output2 <- rbind.data.frame(output2,row)
  
  
}

write.csv( output2 , file = '../Outputs/N14m377170_CramerV_n_CEE_binary_Deprivations.csv')
write.csv( panelsheet , file = '../Outputs/N14m377170_panelsheet_n_CEE_binary_Deprivations.csv')



```

```{r}
plotdata <- data[ n_tenure != 'unknown' ,  .(n = .N), by = c('n_CEE_binary','n_tenure') ]
ggplot(plotdata, aes(fill=n_CEE_binary, y = n, x=n_tenure)) + 
    geom_bar(position="fill", stat="identity")+
    theme_minimal()

plotdata <- data[ ,  .(n = .N), by = c('n_tenure') ]
ggplot(plotdata, aes(fill=n_tenure, y = n, x ='')) + 
    geom_bar(position="fill", stat="identity")+
    coord_flip()+
    theme_minimal()+
    theme(legend.position="bottom")+scale_fill_grey()



  
ggplot(dat = data[ n_CEE_binary == "C-" & n_tenure != 'unknown' ], 
       aes(x= ssimp_nn_construction_age_band, y=stat(count), fill = ssimp_nn_construction_age_band))+
  geom_bar()+
  facet_grid(n_tenure ~ n_propTyp, scale = "free_y") +
  #coord_flip()+
  labs( x = 'Building Age and Property Type', y = 'Number of properties' )+
  theme_minimal()+
  theme(axis.text.y = element_text(hjust = 1, size=6),
        axis.text.x = element_text(angle = 45, hjust = 1, size=7),
        legend.position="none")+
  labs(subtitle = paste0("n=", format(lengths(data[ n_CEE_binary == "C & C+" ])[1], big.mark = ' ') ) ) +
  labs(title = "Building Characteristics of Cross-sectional EPC Records, C-", caption ='Author: Bonnie Buyuklieva, @Bonnie_0000 \n Project: OS Narrate, UCL 2022-23 \nCentre for Advanced Spatial Analysis ')


#ggsave(file="./Age_Property_Type_Tenure_C-.svg", plot=p, width=14, height=14)






transType_baseline <- data[,  .(n = .N), by = c('n_transactTyp') ]
transType <- data[,  .(n = .N), by = c('lad19cd','LAD11NM','n_transactTyp') ]
#note LADCD and LADNM don't always align. Use LADCD




example <- data[ ,  .(n = .N), by = c(measure,'n_propTyp') ]
example <- dcast(example, paste('n_propTyp', "~", measure), value.var = 'n')
```

```{r Map}
#Map Anything
Map_example <- data[ ,  .(n = .N), by = c('ssimp_nn_construction_age_band','lad19cd') ]
Map_example <- dcast(Map_example, paste('lad19cd', "~", 'ssimp_nn_construction_age_band'), value.var = 'n')
Map_example$majority <- colnames(Map_example[,-(1),drop=FALSE])[max.col(Map_example[,-(1),drop=FALSE])]
#Map_example$rowt <- rowSums(Map_example[,- (c(1,length(Map_example) ) )  ,drop=FALSE])
basematrix <- subset( Map_example, select = -c(1, length(Map_example)) )
Map_example$rowt <- rowSums(  basematrix  )

Map_examplePercent <- round(basematrix/Map_example$rowt,2)*100
#Map_examplePercent <- round(Map_example[,-(1),drop=FALSE]/Map_example$rowt,2)*100
#Map_examplePercent$median <- round(median(mean(as.matrix(Map_examplePercent[,2:8]))))#dont need anymore
Map_examplePercent$median <- round(median(mean(as.matrix(Map_examplePercent))))
Map_example <- cbind.data.frame(Map_example,Map_examplePercent[,-(1),drop=FALSE] )





#Map Anything
Map_example <- data[ n_tenure != 'unknown',  .(n = .N), by = c('x_Tenure3_CEE_binary','lad19cd') ]
Map_example <- dcast(Map_example, paste('lad19cd', "~", 'x_Tenure3_CEE_binary'), value.var = 'n')
Map_example$majority <- colnames(Map_example[,-(1),drop=FALSE])[max.col(Map_example[,-(1),drop=FALSE])]
#Map_example$rowt <- rowSums(Map_example[,- (c(1,length(Map_example) ) )  ,drop=FALSE])
basematrix <- subset( Map_example, select = -c(1, length(Map_example)) )
Map_example$rowt <- rowSums(  basematrix  )

Map_examplePercent <- round(basematrix/Map_example$rowt,2)*100
names(Map_examplePercent) <- paste('p%_',names(Map_examplePercent))
#Map_examplePercent <- round(Map_example[,-(1),drop=FALSE]/Map_example$rowt,2)*100
Map_examplePercent$median <- round(median(mean(as.matrix(Map_examplePercent))))
Map_example <- cbind.data.frame(Map_example,Map_examplePercent[,-(1),drop=FALSE] )

Map_example$plot_SubCRentPer_ <- Map_example$`p%_ rental (private) C-` + Map_example$`p%_ rental (social) C-`
#about 20% is will need to change 
median(Map_example$plot_SubCRentPer_)

write.csv(Map_example, './Tenure_C_binary_Map_example.csv')
```

```{r meta_data_table}
cols <- names(data) # colnames
cols_na <- sapply(data, function(x) sum(is.na(x)))

#count of unique factors
l_unique_factors <- sapply(data, function(x) length(unique(x)))
test1 <- as.data.frame(l_unique_factors)
test <- as.data.frame(do.call(cbind, test1))
type <- sapply(data , function(x) typeof(x)) 

cols <- cbind(names = names(data), 
              type = type,
              nas_counts = cols_na, 
              factors = test)
#write.csv(cols, './testMEdel.csv')

```

```{r choose factors}
#get cols with 3-37 factprs

interest_factors_cols <- cols[cols$l_unique_factors < 38 & cols$l_unique_factors > 2, 'names']

#remove some
interest_factors_cols <- setdiff(interest_factors_cols, c("CURRENT_ENERGY_RATING", "n_CEErel","n_CEIrel","n_CEE_binary",
                                                          "CONSTRUCTION_AGE_BAND",# harmonised
                                                          "TENURE", # harmonised
                                                          "TRANSACTION_TYPE",# harmonised 
                                                          "GLAZED_TYPE"#GLAZED_TYPE needs harmonising
                                                          ))
#add some
interest_factors_cols <- c(interest_factors_cols, 
                           'x_PropT3_Tenure3_Age8',
                           'x_PropT3_Age8',
                           'x_PropT3_Tenure3',
                           'X_Tenure3_Age8',
                           'x_Tenure3_habitable_rooms_grp10',
                           'x_Tenure3_habitable_rooms_grp10_PropT3')
```


#for tomorrow: harmonise more from raw.
#interact 
- tenure with age
- tenure age and property type
- tenure age and 



