---
title: "Duplicate EPCs in V10"
author: "Boyana Buyuklieva"
date: "May 20, 2022"
output: html_document
---

#This version is has linear time complexity. 

```{r setup, include=FALSE, echo = T}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(readr)
library(microbenchmark)
library(fasttime)
options(scipen=999)

#get folders
folders <- list.files(path = "../Data/all-domestic-certificates", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
folders <- folders[-342] #remove the .txt


#TEST!
regional_LUT <- fread("../Data/deleteMe_folders_geography_LUT.csv")

setkey(regional_LUT, "Folder")

start.time <- Sys.time()
ubdc_LUT <- fread("../Data/ubdc_link.csv",  
                  select = c("lmk_key","ubdc_uprn"),
                  colClasses = c("lmk_key" = "character",
                                 "ubdc_uprn" = "character"))

setkey(ubdc_LUT,lmk_key)
print(paste('fread:', Sys.time() - start.time)) #aprox 7 mins


checks <- c("INSPECTION_DATE","CURRENT_ENERGY_RATING","CURRENT_ENERGY_EFFICIENCY","LMK_KEY","ubdc_UPRN")

```




# Duplicate Defintion Testing
```{r loop}
longitudinalEPCs_long <- list()
print_counter = 0

#using this instead of directory folders, to sort by region
folders_sorted_by_regional_LUT <- regional_LUT[order(RGN11NM)]$Folder
#replaces the if statement
previous_region <- regional_LUT[order(RGN11NM)]$RGN11NM[1]
mapping <- list() 


start.time <- Sys.time()
for (LA in folders_sorted_by_regional_LUT) {
  
  print(LA)
  
  print_counter = print_counter+1
  if(print_counter %% 20 == 0){print(LA)} 
  
  certificates <- fread(paste0("../Data/all-domestic-certificates/",LA,"/certificates.csv"),
                        colClasses = c(       #'LMK_KEY' = 'character', 
                                              'LODGEMENT_DATETIME' = 'character',
                                              'CURRENT_ENERGY_RATING' = 'character',
                                              'CURRENT_ENERGY_EFFICIENCY' = 'character',
                                              'ADDRESS' = 'character',
                                              'POSTCODE' = 'character',
                                              'UPRN' = 'character',
                                              'UPRN_SOURCE' = 'character',
                                              'LOCAL_AUTHORITY' = 'character',
                                              'LOCAL_AUTHORITY_LABEL' = 'character',
                                              'POSTTOWN' = 'character',
                                              'CONSTITUENCY_LABEL' = 'character',
                                              'TRANSACTION_TYPE' = 'character',
                                              'TENURE' = 'character'))
  
    
  
    current_region <- regional_LUT[LA]$RGN11NM
    certificates[,RGN11NM := current_region]
    certificates[,LAD11NM := regional_LUT[LA]$LAD11NM]
    
    #convert to date.time
    certificates[, INSPECTION_DATE := fastPOSIXct(INSPECTION_DATE, required.components = 3L)] #3 means only the date is required to a conversion to be valid
    
    #Create the Longitudinal Dataset
    #-------------------------------------------------------------------------------------------------------------------------------
    ##LUT dups
    tmp <- ubdc_LUT[certificates$LMK_KEY, 'ubdc_uprn']
    certificates[,ubdc_UPRN := tmp]
    
    ##combined str dups
    certificates[,str_concat := paste(ADDRESS, POSTCODE)]

    ###..make col n_UPRN where this would UPRN, or ubdc_UPRN where its missing
    certificates[ , n_UPRN := UPRN] 
    certificates[ n_UPRN == '',  n_UPRN := ubdc_UPRN]
    
    
    repeat_str <- duplicated(certificates$str_concat)|duplicated(certificates$str_concat, fromLast = T)
    
    #changed syntax because duplicate() won't work. The version of duplicated (duplicated.integer64() does not implement fromLast AND ignores the args! LOL 🥲)
    ## example: duplicated(certificates$n_UPRN, fromLast = T ) [c(6971,14575)] = F, T
    repeat_nUPRN <- (duplicated(certificates, by = "n_UPRN")|duplicated(certificates, by = "n_UPRN", fromLast = T)) & !(certificates$n_UPRN == '')
 

    dup_idx <- union(which(repeat_str),which(repeat_nUPRN))
    duplicated_certificates <- as.data.table(certificates[dup_idx,])
    duplicated_certificates <- duplicated_certificates[order(UPRN,str_concat,ubdc_UPRN, INSPECTION_DATE),]
    #View(duplicated_certificates[,..check])# these duplicates seems fine
    #duplicated_certificates[ n_UPRN == '10009711048',..check]
    
    
    
    #Problem 1: Assigning UPRNs
    ##CASE 1: idential string address repeats with UPRN value sometimes missing
    ## example: "domestic-E06000001-Hartlepool":'Mount Oswald Nursing Home, 16 Hutton Avenue TS26 9PN'
    dict <- duplicated_certificates[ !is.na(n_UPRN), c('str_concat','n_UPRN','INSPECTION_DATE')]
    
    ##CASE 2: idential string address repeats with different UPRN values
    ## example: "domestic-E06000001-Hartlepool":"Gospel Hall, 32 Town Wall TS24 0JQ"
    ## resolution is to assume the most recent UPRN to be right one
    #potential problem
    dict <-  dict[order(-INSPECTION_DATE), c('str_concat','n_UPRN')]
    dict <-  dict[!duplicated(str_concat), ]
    dict <- setkey(as.data.table(dict), str_concat)
    duplicated_certificates  <- duplicated_certificates[,n_UPRN := dict[duplicated_certificates$str_concat, 'n_UPRN']] 
    duplicated_certificates  <- duplicated_certificates[order(n_UPRN, str_concat, -INSPECTION_DATE),]
    duplicated_certificates$n_GRP <-ifelse(is.na(duplicated_certificates$n_UPRN), duplicated_certificates$str_concat, duplicated_certificates$n_UPRN )
    #View(duplicated_certificates[, c('n_GRP','str_concat','n_UPRN','INSPECTION_DATE')])
    
    #Output: Append to long list
    longitudinalEPCs_long<- rbindlist(list(longitudinalEPCs_long,duplicated_certificates ))
    #-------------------------------------------------------------------------------------------------------------------------------
    
    #Create the Crossectional Dataset (include only most recent obvervations of repeat entries)
    #------------------------------------------------------------------------------------------------------------------------------
    ###Problem 2: Identifing all repeats, except the latest observations to create blacklist
    tmp_mapping_blacklist <- as.data.table(duplicated_certificates[which( !duplicated(duplicated_certificates$n_GRP) ),]$LMK_KEY )
    tmp_mapping <- certificates[!certificates$LMK_KEY %in% tmp_mapping_blacklist$V1,] #keep those outside the blacklist
    mapping <- rbindlist(list(mapping,tmp_mapping ))
   #------------------------------------------------------------------------------------------------------------------------------
}
print(paste('loop time:', Sys.time() - start.time))#"loop time: 2.35320606278049"
```


