---
title: "Tenure - EPCs in V10"
author: "Boyana Buyuklieva"
date: "May 4, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(data.table)
library(fasttime)
library(readxl)

loadRData <- function(fileName){
    #loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}

#get folders
cross_data <- list.files(path = "../Data/RData_crossSectional", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
cross_data <- gsub(".RData","",as.character(cross_data))
cross_data <- gsub("crossSectional_","",as.character(cross_data))


#get loopUp
LUT_tenure <- read_excel("../Data/OS-N_EPC_v10_LUT+dictionaries.xlsx", sheet = "TENURE",range = cell_cols("B:C"))
LUT_builtForm <- read_excel("../Data/OS-N_EPC_v10_LUT+dictionaries.xlsx", sheet = "BUILT_FORM",range = cell_cols("B:C"))
```


```{r crossSectional_loop}

start.time <- Sys.time()
  
for (region in cross_data) {
  #region = cross_data[4] #testing
  print(paste(region, Sys.time()))
  
  tmp <- loadRData(paste0("../Data/RData_crossSectional/crossSectional_",region,".RData") )
  
  #CREATE NEW COLUMNS
  #N1: info on UPRNs differences and NAs
  tmp[, n_erNoUPRN := ifelse(UPRN == ubdc_UPRN,'same','diffUPRNs')]
  tmp[, n_erNoUPRN := ifelse(UPRN == "" | is.na(UPRN),'diffUPRNs_NA_UPRN',n_erNoUPRN) ]
  tmp[, n_erNoUPRN := ifelse(ubdc_UPRN == ""| is.na(ubdc_UPRN),'diffUPRNs_NA_ubdc_UPRN',n_erNoUPRN) ]
  tmp[, n_erNoUPRN := ifelse(n_UPRN == "" | is.na(n_UPRN),'noUPRN',n_erNoUPRN) ]

  
  #N2: create C relative column
  tmp[, n_Crel:= ifelse(CURRENT_ENERGY_RATING == 'C', 'C', 
                                ifelse(CURRENT_ENERGY_RATING %in% c('A', 'B'), 'C+', 
                                       ifelse(CURRENT_ENERGY_RATING %in% c('D', 'E','F','G'),'C-','NA' )))]
  #tmp[CURRENT_ENERGY_RATING =="INVALID!", ]$CURRENT_ENERGY_EFFICIENCY
  tmp[n_Crel =="NA", n_Crel:= ifelse(CURRENT_ENERGY_EFFICIENCY > 100, 'C+', 'C-')]
  
  
  #N3: create new Tenure column
  LUT_colum <- LUT_tenure[match(tmp$TENURE, LUT_tenure$tenure_factors),"harmonisation"]
  tmp[,n_tenure := LUT_colum]
  tmp[is.na(n_tenure),n_tenure := 'unknown'] #deals with NAs
      
  #N4: create new Built Form column
  LUT_colum <- LUT_builtForm[match(tmp$BUILT_FORM, LUT_builtForm$BUILT_FORMfactors),"harmonisation"]
  tmp[,n_builtForm := LUT_colum]
  tmp[is.na(n_builtForm),n_builtForm := 'unknown'] 
      

  
  tmp <- tmp[, c("LAD11NM","LMK_KEY","n_UPRN","n_erNoUPRN","CURRENT_ENERGY_EFFICIENCY","n_Crel", "n_tenure", "n_builtForm","TENURE","BUILT_FORM","PROPERTY_TYPE","POTENTIAL_ENERGY_EFFICIENCY","str_concat","UPRN","ubdc_UPRN")]
  save(tmp, file = paste0("../Outputs/WIP_crossSectional/crossSectional_baseline_",region,".RData") )
}

print(Sys.time()-start.time)
```



#simple 2D

```{r LAD_CRel_summary - works}
LAD_table <- list()


for(region in cross_data){
  print(paste(region, Sys.time()))
  tmp_tally <- loadRData(paste0("../Outputs/WIP_crossSectional/crossSectional_baseline_",region,".RData") )
  
  tmp_tally[,n_CrelXbuiltForm := paste(n_Crel,BUILT_FORM )]
  #View(tmp_tally[1:500,c('n_CrelXbuiltForm','n_Crel','BUILT_FORM')])
  
  
  long <- tmp_tally[,.N, by = c('LAD11NM', 'n_CrelXbuiltForm')]
  
  test <- reshape(long, idvar = "LAD11NM", timevar = "n_CrelXbuiltForm", direction = "wide")
  test$region <- region

  LAD_table <- rbind(LAD_table,test, fill = TRUE)
  
}

LAD_table[is.na(LAD_table)] <- "0"#set 0 for NAs
write.xlsx(LAD_table,
             file = "../Data/LAD_CrossSectional_Summary.xlsx", sheetName="n_CrelXbuiltForm", append=TRUE)
```


#simple 1D
```{r LAD_erNoUPRN - works}
LAD_table <- list()


for(region in cross_data){
  print(paste(region, Sys.time()))
  tmp_tally <- loadRData(paste0("../Outputs/WIP_crossSectional/crossSectional_baseline_",region,".RData") )
  long <- tmp_tally[,.N, by = c('LAD11NM', 'n_erNoUPRN')]
  
  test <- reshape(long, idvar = "LAD11NM", timevar = "n_erNoUPRN", direction = "wide")
  test$region <- region

  LAD_table <- rbind(LAD_table,test, fill = TRUE)
  
}

LAD_table[is.na(LAD_table)] <- "0"#set 0 for NAs
write.xlsx(LAD_table,
             file = "../Data/LAD_CrossSectional_Summary.xlsx", sheetName="erNoUPRN", append=TRUE)
```

```{r LAD_CRel_summary - works}
LAD_table <- list()


for(region in cross_data){
  print(paste(region, Sys.time()))
  tmp_tally <- loadRData(paste0("../Outputs/WIP_crossSectional/crossSectional_baseline_",region,".RData") )
  
  long <- tmp_tally[,.N, by = c('LAD11NM', 'n_Crel')]
  
  test <- reshape(long, idvar = "LAD11NM", timevar = "n_Crel", direction = "wide")
  test$region <- region

  LAD_table <- rbind(LAD_table,test, fill = TRUE)
  
}

LAD_table[is.na(LAD_table)] <- "0"#set 0 for NAs
write.xlsx(LAD_table,
             file = "../Data/LAD_CrossSectional_Summary.xlsx", sheetName="CRel_Summary", append=TRUE)
```


```{r check_total_number_of_cols}
sum <- 0

for(region in cross_data){
  tmp_tally <- loadRData(paste0("../Outputs/WIP_crossSectional/crossSectional_baseline_",region,".RData") )
  sum <- sum+ lengths(tmp_tally)[1]
   
}
```