---
title: "P3_CrossSectional_EDA"
author: "Boyana Buyuklieva"
date: "August 30, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(data.table)
library(readr)
library(foreign)
library(ggExtra)


loadRData <- function(fileName){
    #loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}

big_Dt_CSsubset_N6M7 <- loadRData("../Outputs/WIP_crossSectional/ONSUD_crossSectional_subset_N16744771.RData")
fctr_levels <- c("C+","C","C-")
big_Dt_CSsubset_N6M7[,n_Crel := factor(n_Crel, levels = fctr_levels, ordered = T)]


```


```{r}
big_Dt_CSsubset_N6M7[, n_potCEE := POTENTIAL_ENERGY_EFFICIENCY - CURRENT_ENERGY_EFFICIENCY]
big_Dt_CSsubset_N6M7[, n_potEIC := ENVIRONMENT_IMPACT_POTENTIAL - ENVIRONMENT_IMPACT_CURRENT]
```


```{r}
vis_subset_N6M7 <- big_Dt_CSsubset_N6M7[sample(nrow(big_Dt_CSsubset_N6M7), 2000, replace = F ), ]
```





# Energy Efficiency

```{r CEE}
start_time <- Sys.time()

counts <- sum(which( vis_subset_N6M7$POTENTIAL_ENERGY_EFFICIENCY>100))
percents <- round(counts/length(vis_subset_N6M7$POTENTIAL_ENERGY_EFFICIENCY),0)
counts <- format(counts, big.mark = ' ', trim = T)

p <- ggplot(vis_subset_N6M7, aes(x=POTENTIAL_ENERGY_EFFICIENCY, y = '')) +
      geom_point() +
      #geom_boxplot(width = .2)+
      geom_boxplot()+
      annotate(geom="label", 
                label= paste0("Over 100:\n",counts ,'\n ~',percents,'%'),
                x=110, y=1.2, angle = 90,
                size = 2)

 ggMarginal(p, type="density") + theme_minimal()
 
 
print(Sys.time() - start_time)
```


```{r PEE}
start_time <- Sys.time()

counts <- sum(which( vis_subset_N6M7$POTENTIAL_ENERGY_EFFICIENCY>100))
percents <- round(counts/length(vis_subset_N6M7$POTENTIAL_ENERGY_EFFICIENCY),0)
counts <- format(counts, big.mark = ' ', trim = T)

p <- ggplot(vis_subset_N6M7, aes(x=POTENTIAL_ENERGY_EFFICIENCY, y = '')) +
      geom_point() +
      #geom_boxplot(width = .2)+
      geom_boxplot()+
      annotate(geom="label", 
                label= paste0("Over 100:\n",counts ,'\n ~',percents,'%'),
                x=110, y=1.2, angle = 90,
                size = 2)

 ggMarginal(p, type="density") + theme_minimal()
 
 
print(Sys.time() - start_time)
```


```{r Potential Minus Current EE}
start_time <- Sys.time()

counts <- sum(which( vis_subset_N6M7$n_potCEE>100))
percents <- round(counts/length(vis_subset_N6M7$n_potCEE),0)
counts <- format(counts, big.mark = ' ', trim = T)

p <- ggplot(vis_subset_N6M7, aes(x=n_potCEE, y = '')) +
      geom_point() +
      #geom_boxplot(width = .2)+
      geom_boxplot()+
      annotate(geom="label", 
                label= paste0("Over 100:\n",counts ,'\n ~',percents,'%'),
                x=110, y=1.2, angle = 90,
                size = 2)

 ggMarginal(p, type="density") + theme_minimal()
 
 
print(Sys.time() - start_time)#took 9 mins
```


# Environmental Impact





###Deal with:
```{r attached_IMDs}
#multiple deprivation EW
IMD19<- read.dbf("../Data/_shapefiles/Lower_Super_Output_Area_(LSOA)_IMD_2019__(OSGB1936)/Lower_Super_Output_Area_(LSOA)_IMD_2019__(OSGB1936).dbf")

#income deprivation E
income_imd2019lsoa_E <- fread("../Data/imd2019lsoa/imd2019lsoa.csv",
                     drop="Units", #empty column anyway
                     colClasses = c( "FeatureCode" = "character",
                                     "Measurement" = "character",
                                     "Value" = "numeric",
                                     "Indices of Deprivation" = "character"))

#Measurements are: "Rank"   "Decile" "Score"
#income_imd2019lsoa_E <- setNames(income_imd2019lsoa_E, c("lsoa11cd","Date","Measurement","Value","Indices of Deprivation") )
setnames(income_imd2019lsoa_E, c("FeatureCode"), c("lsoa11cd"))

EDA_cols <- read_csv("../Data/EDA_colour_scheme.csv")
#EDA_cols <- subset(EDA_cols[EDA_cols$geography_name %in%  cross_data, ])

#formatting:
lettermapping <-  data.frame( letter = c('A','B','C','D','E','F','G'), 
                              cutoff = c(92, 81, 69, 55, 39, 21, 0))

#Add IMD
big_Dt_CSsubset_N6M7[IMD19,  on = 'lsoa11cd', c('n_IMDRank','n_IMDDecil') := .(IMDRank,IMDDecil)]

#Add IoD
##can select other IoD here
imd_bincome <-  income_imd2019lsoa_E[ `Indices of Deprivation` == "b. Income Deprivation Domain",]
imd_bincome <-dcast(imd_bincome, lsoa11cd ~ Measurement, value.var = c("Value"))
big_Dt_CSsubset_N6M7[imd_bincome,  on = 'lsoa11cd', c('n_bIoDRank_income','n_bIoDDecil_income') := .(Rank,Decile)]
```


