---
title: "P3_CrossSectional_EDA"
author: "Boyana Buyuklieva"
date: "August 30, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache.lazy = FALSE)
library(dplyr)
library(tidyverse)
library(data.table)
library(readr)
library(foreign)
library(ggExtra)


loadRData <- function(fileName){
    #loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}

big_Dt_CSsubset_N6M7 <- loadRData("../Outputs/WIP_crossSectional/ONSUD_crossSectional_subset_N16744771.RData")
fctr_levels <- c("C+","C","C-")
big_Dt_CSsubset_N6M7[,n_Crel := factor(n_Crel, levels = fctr_levels, ordered = T)]

big_Dt_CSsubset_N6M7[, n_potEE := POTENTIAL_ENERGY_EFFICIENCY - CURRENT_ENERGY_EFFICIENCY]
big_Dt_CSsubset_N6M7[, n_potIE := ENVIRONMENT_IMPACT_POTENTIAL - ENVIRONMENT_IMPACT_CURRENT]

#formatting:
lettermapping <-  data.frame( letter = c('A','B','C','D','E','F','G'), 
                              cutoff = c(92, 81, 69, 55, 39, 21, 0))
```

```{r}
#all empty
nas <- which(is.na(big_Dt_CSsubset_N6M7$CURRENT_ENERGY_EFFICIENCY))

nas <- which(is.na(big_Dt_CSsubset_N6M7$POTENTIAL_ENERGY_EFFICIENCY))

nas <- which(is.na(big_Dt_CSsubset_N6M7$n_potEE))


nas <- which(is.na(big_Dt_CSsubset_N6M7$ENVIRONMENT_IMPACT_CURRENT))

nas <- which(is.na(big_Dt_CSsubset_N6M7$ENVIRONMENT_IMPACT_POTENTIAL))

nas <- which(is.na(big_Dt_CSsubset_N6M7$n_potEIC))
```



```{r , cache = TRUE}
#vis_subset_N6M7 <- big_Dt_CSsubset_N6M7[sample(nrow(big_Dt_CSsubset_N6M7), 2000, replace = F ), ]
vis_subset_N6M7 <- big_Dt_CSsubset_N6M7
```

# Energy Efficiency
```{r CEE, cache = TRUE}
start_time <- Sys.time()

counts <- sum(vis_subset_N6M7$CURRENT_ENERGY_EFFICIENCY>100)
percents <- round(counts/length(vis_subset_N6M7$CURRENT_ENERGY_EFFICIENCY),0)
counts <- format(counts, big.mark = ' ', trim = T)

p <- ggplot(vis_subset_N6M7, aes(x=CURRENT_ENERGY_EFFICIENCY + 0.001, y = '')) +
      geom_point() +
      #geom_boxplot(width = .2)+
      geom_boxplot()+
      annotate(geom="label", 
                label= paste0("Over 100:\n",counts ,'\n ~',percents,'%'),
                x=110, y=1.2, angle = 90,
                size = 2)+
  scale_x_continuous(name = 'Current Energy Efficiency' , breaks= lettermapping$cutoff)+
  theme_minimal()


ggMarginal(p, type="density") 
rm(p)
 
 
 
print(Sys.time() - start_time)
```

```{r PEE, cache = TRUE}
start_time <- Sys.time()

counts <- sum( vis_subset_N6M7$POTENTIAL_ENERGY_EFFICIENCY>100)
percents <- round(counts/length(vis_subset_N6M7$POTENTIAL_ENERGY_EFFICIENCY),0)
counts <- format(counts, big.mark = ' ', trim = T)

p <- ggplot(vis_subset_N6M7, aes(x=POTENTIAL_ENERGY_EFFICIENCY, y = '')) +
      geom_point() +
      #geom_boxplot(width = .2)+
      geom_boxplot()+
      annotate(geom="label", 
                label= paste0("Over 100:\n",counts ,'\n ~',percents,'%'),
                x=110, y=1.2, angle = 90,
                size = 2)+
  scale_x_continuous(name = 'Potential Energy Efficiency' , breaks= lettermapping$cutoff)+
  theme_minimal()

ggMarginal(p, type="density") 
rm(p)

print(Sys.time() - start_time)
```


```{r PotentialEE, cache = TRUE}
start_time <- Sys.time()

counts <- sum( vis_subset_N6M7$n_potEE>100)
percents <- round(counts/length(vis_subset_N6M7$n_potEE),0)
counts <- format(counts, big.mark = ' ', trim = T)

p <- ggplot(vis_subset_N6M7, aes(x=n_potEE, y = '')) +
      geom_point() +
      #geom_boxplot(width = .2)+
      geom_boxplot()+
      annotate(geom="label", 
                label= paste0("Over 100:\n",counts ,'\n ~',percents,'%'),
                x=110, y=1.2, angle = 90,
                size = 2)+ theme_minimal()

ggMarginal(p, type="density") 
rm(p)
 
print(Sys.time() - start_time)#took 9 mins
```


# Environmental Impact
```{r EIC, cache = TRUE}
start_time <- Sys.time()

counts <- sum(vis_subset_N6M7$ENVIRONMENT_IMPACT_CURRENT>100)
percents <- round(counts/length(vis_subset_N6M7$ENVIRONMENT_IMPACT_CURRENT),0)
counts <- format(counts, big.mark = ' ', trim = T)

p <- ggplot(vis_subset_N6M7, aes(x=ENVIRONMENT_IMPACT_CURRENT + 0.001, y = '')) +
      geom_point() +
      #geom_boxplot(width = .2)+
      geom_boxplot()+
      annotate(geom="label", 
                label= paste0("Over 100:\n",counts ,'\n ~',percents,'%'),
                x=110, y=1.2, angle = 90,
                size = 2)+
  scale_x_continuous(name = 'Current Energy Efficiency' , breaks= lettermapping$cutoff)+
  theme_minimal()


ggMarginal(p, type="density") 
rm(p)
 
 
 
print(Sys.time() - start_time)
```

```{r EIP, cache = TRUE}
start_time <- Sys.time()

counts <- sum( vis_subset_N6M7$ENVIRONMENT_IMPACT_POTENTIAL>100)
percents <- round(counts/length(vis_subset_N6M7$ENVIRONMENT_IMPACT_POTENTIAL),0)
counts <- format(counts, big.mark = ' ', trim = T)

p <- ggplot(vis_subset_N6M7, aes(x=ENVIRONMENT_IMPACT_POTENTIAL, y = '')) +
      geom_point() +
      #geom_boxplot(width = .2)+
      geom_boxplot()+
      annotate(geom="label", 
                label= paste0("Over 100:\n",counts ,'\n ~',percents,'%'),
                x=110, y=1.2, angle = 90,
                size = 2)+
  scale_x_continuous(name = 'Potential Energy Efficiency' , breaks= lettermapping$cutoff)+
  theme_minimal()

ggMarginal(p, type="density") 
rm(p)

print(Sys.time() - start_time)
```


```{r PotentialIE, cache = TRUE}
start_time <- Sys.time()

counts <- sum( vis_subset_N6M7$n_potIE>100)
percents <- round(counts/length(vis_subset_N6M7$n_potIE),0)
counts <- format(counts, big.mark = ' ', trim = T)

p <- ggplot(vis_subset_N6M7, aes(x=n_potIE, y = '')) +
      geom_point() +
      #geom_boxplot(width = .2)+
      geom_boxplot()+
      annotate(geom="label", 
                label= paste0("Over 100:\n",counts ,'\n ~',percents,'%'),
                x=110, y=1.2, angle = 90,
                size = 2)+ theme_minimal()

ggMarginal(p, type="density") 
rm(p)
 
print(Sys.time() - start_time)#took 9 mins
```







# Area
```{r Potential Minus Current EE, cache = TRUE}
start_time <- Sys.time()

labels <-  quantile(vis_subset_N6M7$TOTAL_FLOOR_AREA, c(0.1,.25,.5,.75,0.9))


ggplot(vis_subset_N6M7[TOTAL_FLOOR_AREA < quantile(vis_subset_N6M7$TOTAL_FLOOR_AREA, 0.9), ], 
       aes(x=TOTAL_FLOOR_AREA, y = '')) +
       geom_boxplot()+
       geom_jitter( alpha = .1, size = 1) +
       scale_x_continuous(limits = quantile(vis_subset_N6M7$TOTAL_FLOOR_AREA, c(0.1, 0.9)))

  

# +#https://stackoverflow.com/questions/56434187/label-whiskers-on-ggplot-boxplot-when-there-are-outliers
#   stat_summary(
#     aes(label=sprintf("%1.1f", ..y..)),
#     geom="text", 
#     fun.x = labels,
#     position=position_nudge(x=0.33), 
#     size=3.5)
#   
#https://stackoverflow.com/questions/5677885/ignore-outliers-in-ggplot2-boxplot

 
print(Sys.time() - start_time)#took 9 mins
```


# Rooms
```{r}
p <- ggplot(vis_subset_N6M7, aes(NUMBER_HEATED_ROOMS, NUMBER_HABITABLE_ROOMS)) + geom_point() + theme_minimal()
ggMarginal(p, type = "histogram")
```


```{r}

```



