---
title: "P3_CrossSectional_EDA"
author: "Boyana Buyuklieva"
date: "August 30, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(data.table)
library(readxl)
library(readr)



loadRData <- function(fileName){
    #loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}

#get folders
cross_data <- list.files(path = "../Data/RData_crossSectional", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

cross_data <- gsub(".RData","",as.character(cross_data))
cross_data <- gsub("crossSectional_","",as.character(cross_data))



EDA_cols <- read_csv("../Data/EDA_colour_scheme.csv")
EDA_cols <- subset(EDA_cols[EDA_cols$geography_name %in%  cross_data, ])
```



```{r assign region to unknown entries}
unknown_region_df<- loadRData( paste0("../Outputs/WIP_crossSectional/crossSectional_baseline_","Unknown",".RData") )
setkey(unknown_region_df, n_UPRN)

tmp <- unknown_region_df #head(unknown_region_df, 100)
tmp$lsoa11cd <- NULL

for(ONSUD in EDA_cols$ONSUD){
  if(is.na(ONSUD))break;  
  ONSUD_MAY_2020 <- fread(paste0("../Data/ONSUD_MAY_2020/Data/ONSUD_MAY_2020_",ONSUD,".csv"),
                          colClasses = c("uprn" = "character"))
  setkey(ONSUD_MAY_2020, uprn)

  tmp$uprn <- tmp$n_UPRN
  tmp[ONSUD_MAY_2020, on = 'uprn', lsoa11cd := i.lsoa11cd]
  tmp[ONSUD_MAY_2020, on = 'uprn', rgn17cd := i.rgn17cd]
  #print(ONSUD)
}

dt_for_assignemnet <- tmp[!is.na(lsoa11cd),]
#8 249 of 9 794 are assigned a LSOA, using UPRNs only 

unknown <- tmp[is.na(lsoa11cd),]
unknown$region <- "Unknown"


for (WIP in EDA_cols$geography_name) {
 if(WIP == "Unknown") break; 
  
 region_df<- loadRData( paste0("../Outputs/WIP_crossSectional/crossSectional_baseline_",WIP,".RData") )
 region_df$uprn <- region_df$n_UPRN
 setkey(region_df, uprn)#setting this as a key, as its the smaller dt
 
 ONSUD <- EDA_cols$ONSUD[ EDA_cols$geography_name == WIP]
 ONSUD_MAY_2020 <- fread(paste0("../Data/ONSUD_MAY_2020/Data/ONSUD_MAY_2020_",ONSUD,".csv"),
                          colClasses = c("uprn" = "character"))
 setkey(ONSUD_MAY_2020, uprn)
 
 region_df[ONSUD_MAY_2020, on = 'uprn', lsoa11cd := i.lsoa11cd]
 region_df[ONSUD_MAY_2020, on = 'uprn', rgn17cd := i.rgn17cd]
 
 assign <- EDA_cols$ONSUD_rgn17cd[ EDA_cols$geography_name == WIP]
 
 output <- rbindlist(list(region_df[!is.na(lsoa11cd)], dt_for_assignemnet[rgn17cd == assign ,]),
       use.names=TRUE, fill=FALSE, idcol=NULL)
 
 if(F){
  save(output, file = paste0("../Outputs/WIP_crossSectional/ONSUD_crossSectional_baseline_",WIP,".RData") ) 
 }
 
 
 tmp_unknown <- region_df[is.na(lsoa11cd)]
 tmp_unknown$region <- WIP
   
 unknown <- rbindlist(list(unknown, tmp_unknown),
       use.names=TRUE, fill=FALSE, idcol=NULL)
}

if(F){
 save(unknown, file = paste0("../Outputs/WIP_crossSectional/ONSUD_crossSectional_baseline_","Unknown",".RData") ) 
}

rm(unknown)  
```

