---
title: "P3_CrossSectional_EDA"
author: "Boyana Buyuklieva"
date: "August 30, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache.lazy = FALSE)
library(dplyr)
library(tidyverse)
library(data.table)
library(readr)
library(foreign)
library(ggExtra)
library(gridExtra)


loadRData <- function(fileName){
    #loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}

big_Dt_CSsubset_N6M7 <- loadRData("../Outputs/WIP_crossSectional/ONSUD_crossSectional_subset_N16744771.RData")
fctr_levels <- c("C+","C","C-")
big_Dt_CSsubset_N6M7[,n_Crel := factor(n_Crel, levels = fctr_levels, ordered = T)]

#tally <- big_Dt_CSsubset_N6M7[, .(n = .N) ,by=NUMBER_HABITABLE_ROOMS ]
big_Dt_CSsubset_N6M7[, NUMBER_HABITABLE_ROOMS:=as.integer(NUMBER_HABITABLE_ROOMS)]

fctr_levels <- c(paste0(seq(1,6,1), 'HR'), '+7HR' )
big_Dt_CSsubset_N6M7[ , n_habitable_rooms_grp := ifelse( NUMBER_HABITABLE_ROOMS>6,'+7HR', paste0(NUMBER_HABITABLE_ROOMS,'HR'))]
big_Dt_CSsubset_N6M7[,n_habitable_rooms_grp := factor(n_habitable_rooms_grp, levels = fctr_levels, ordered = T)]



big_Dt_CSsubset_N6M7[, n_CURRENT_ENERGY_EFFICIENCY := ifelse( CURRENT_ENERGY_EFFICIENCY>100 ,101, CURRENT_ENERGY_EFFICIENCY)]
big_Dt_CSsubset_N6M7[, n_POTENTIAL_ENERGY_EFFICIENCY := ifelse( POTENTIAL_ENERGY_EFFICIENCY>100 ,101, POTENTIAL_ENERGY_EFFICIENCY)]

big_Dt_CSsubset_N6M7[, n_ENVIRONMENT_IMPACT_CURRENT := ifelse( ENVIRONMENT_IMPACT_CURRENT>100 ,101, ENVIRONMENT_IMPACT_CURRENT)]
big_Dt_CSsubset_N6M7[, n_ENVIRONMENT_IMPACT_POTENTIAL := ifelse( ENVIRONMENT_IMPACT_POTENTIAL>100 ,101, ENVIRONMENT_IMPACT_POTENTIAL)]


big_Dt_CSsubset_N6M7[, n_potEE := n_POTENTIAL_ENERGY_EFFICIENCY - n_CURRENT_ENERGY_EFFICIENCY]
big_Dt_CSsubset_N6M7[, n_potIE := n_ENVIRONMENT_IMPACT_POTENTIAL - n_ENVIRONMENT_IMPACT_CURRENT]

#formatting:
lettermapping <-  data.frame( letter = c('A','B','C','D','E','F','G'), 
                              cutoff = c(92, 81, 69, 55, 39, 21, 0))

```

```{r}
#contains nas
nas <- which(is.na(big_Dt_CSsubset_N6M7$TOTAL_FLOOR_AREA)) 
nas

nas <- sum(is.na(big_Dt_CSsubset_N6M7$NUMBER_HEATED_ROOMS))
print(paste( 'NUMBER_HEATED_ROOMS empty: ', nas))

nas <- sum(is.na(big_Dt_CSsubset_N6M7$NUMBER_HABITABLE_ROOMS))
print(paste( 'NUMBER_HABITABLE_ROOMS empty: ', nas))
```


```{r}
cols <- c('TOTAL_FLOOR_AREA','NUMBER_HEATED_ROOMS','NUMBER_HABITABLE_ROOMS',
          'n_habitable_rooms_grp','n_CURRENT_ENERGY_EFFICIENCY','n_ENVIRONMENT_IMPACT_CURRENT',
          'n_builtForm','PROPERTY_TYPE')

big_Dt_CSsubset_N6M7 <- big_Dt_CSsubset_N6M7[!is.na(TOTAL_FLOOR_AREA),]
#vis_subset_N16M7 <- big_Dt_CSsubset_N6M7[sample(nrow(big_Dt_CSsubset_N6M7), 2000, replace = F ), ..cols ]
vis_subset_N16M7 <- big_Dt_CSsubset_N6M7[ ,..cols]


```


# Area
```{r Area95th, cache = TRUE}
start_time <- Sys.time()

ggplot(vis_subset_N16M7, 
       aes(TOTAL_FLOOR_AREA)) +
       geom_density()+
       labs(title = "Floor Area", subtitle = paste0("Subset n=", lengths(vis_subset_N16M7[!is.na(TOTAL_FLOOR_AREA), ])[1]))+
       theme_minimal()

print(Sys.time() - start_time)#took 9 mins
```


```{r }
#this takes ages
start_time <- Sys.time()

subset_P95 <- vis_subset_N16M7[TOTAL_FLOOR_AREA <= quantile(vis_subset_N16M7$TOTAL_FLOOR_AREA, 0.95, na.rm = T), ]
labels <- round(quantile(subset_P95$TOTAL_FLOOR_AREA, c(0,.25,.5,.75,1), na.rm = T),0)

n_label <- format(lengths(vis_subset_N16M7)[1], big.mark = ' ')

ggplot(subset_P95, 
       aes(x=TOTAL_FLOOR_AREA, y = '')) +
       geom_boxplot()+
       scale_x_continuous(breaks = labels, labels = labels)+ 
       labs(title = "Floor Area (95th Percentile)", subtitle = paste0("Subset n=", n_label),
            x = 'Floor Area in m2')
```




```{r last}
if(F){
  #this takes ages
start_time <- Sys.time()

subset_P95 <- vis_subset_N16M7[TOTAL_FLOOR_AREA <= quantile(vis_subset_N16M7$TOTAL_FLOOR_AREA, 0.95, na.rm = T), ]
labels <- round(quantile(subset_P95$TOTAL_FLOOR_AREA, c(0,.25,.5,.75,1), na.rm = T),0)

n_label <- format(lengths(vis_subset_N16M7)[1], big.mark = ' ')

p <- ggplot(subset_P95, 
       aes(x=TOTAL_FLOOR_AREA, y = '')) +
       geom_boxplot()+
       geom_jitter( alpha = .01, size = .1) +
       scale_x_continuous(breaks = labels, labels = labels)+ 
       labs(title = "Floor Area (95th Percentile)", subtitle = paste0("Subset n=", n_label),
            x = 'Floor Area in m2')

ggMarginal(p, type="density") 

print(Sys.time() - start_time)#took 9 mins
}

```

# Rooms
```{r}
subset_n <- lengths(vis_subset_N16M7[!is.na(NUMBER_HEATED_ROOMS) & !is.na(NUMBER_HABITABLE_ROOMS),])[1]
subset_n <- format(subset_n, big.mark = ' ', trim = T)


p <- ggplot(vis_subset_N16M7[!is.na(NUMBER_HEATED_ROOMS) & !is.na(NUMBER_HABITABLE_ROOMS),],
            aes(NUMBER_HEATED_ROOMS, NUMBER_HABITABLE_ROOMS)) + geom_point()+
  labs(caption = paste('N (non-empty) = ', subset_n)) + 
  theme_minimal()

ggMarginal(p, type = "histogram")
```


```{r}
  ggplot(vis_subset_N16M7[!is.na(NUMBER_HEATED_ROOMS),],
            aes(NUMBER_HEATED_ROOMS)) + 
  geom_bar()+
  labs(caption = paste('N (non-empty) = ', subset_n)) + 
  theme_minimal()
```
```{r CEE HR}
##For heated rooms groups: slee
#Denisty of floorspace by heated rooms, box plot 
#Check EPCs, by tenure and deprivation, group by number of rooms

  ggplot(vis_subset_N16M7[!is.na(n_habitable_rooms_grp),], aes(x = n_CURRENT_ENERGY_EFFICIENCY, colour = n_habitable_rooms_grp)) +
  #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
  stat_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.6)+ 
  annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  #theme_classic() +
  theme_minimal()+
  scale_colour_viridis_d(option = "plasma", direction	= -1)+ 
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_x_continuous(name = 'Current Energy Efficiency' , breaks= lettermapping$cutoff)



```




```{r}
#facetgrid: tenure x property type, region
  ggplot(vis_subset_N16M7[!is.na(n_habitable_rooms_grp),], aes(x = n_CURRENT_ENERGY_EFFICIENCY, colour = n_habitable_rooms_grp)) +
  #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
  stat_density(lwd = 1, linetype = 1, position="identity",geom="line", bw = 2)+
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.3)+
  geom_vline( xintercept =  c(69,81), colour = 'black', size=.3)+
  #annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_colour_viridis_d(option = "plasma", direction	= -1)+ 
  scale_x_continuous(name = 'Current Energy Efficiency' , breaks= lettermapping$cutoff)+
  facet_grid(rows = vars(PROPERTY_TYPE),vars(n_builtForm))
```
```{r}
#facetgrid: tenure x property type, region
  ggplot(vis_subset_N16M7[!is.na(n_habitable_rooms_grp),], aes(x = n_ENVIRONMENT_IMPACT_CURRENT, colour = n_habitable_rooms_grp)) +
  #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
  stat_density(lwd = 1, linetype = 1, position="identity",geom="line", bw = 2)+
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.3)+
  geom_vline( xintercept =  c(69,81), colour = 'black', size=.3)+
  #annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_colour_viridis_d(option = "plasma", direction	= -1)+ 
  scale_x_continuous(name = 'Current Environmental Impact' , breaks= lettermapping$cutoff)+
  facet_grid(rows = vars(PROPERTY_TYPE),vars(n_builtForm))
```



```{r}
##For heated rooms groups: slee
#Denisty of floorspace by heated rooms, box plot 
#Check EPCs, by tenure and deprivation, group by number of rooms

  ggplot(vis_subset_N16M7[!is.na(n_habitable_rooms_grp),], aes(x = n_ENVIRONMENT_IMPACT_CURRENT, colour = n_habitable_rooms_grp)) +
  #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
  stat_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.6)+ 
  annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  #theme_classic() +
  theme_minimal()+
  scale_colour_viridis_d(option = "plasma", direction	= -1)+ 
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_x_continuous(name = 'Current Environmental Impact' , breaks= lettermapping$cutoff)
```


```{r CEI addingInTenure BF1}
cols <- c('TOTAL_FLOOR_AREA','NUMBER_HEATED_ROOMS','NUMBER_HABITABLE_ROOMS',
          'n_habitable_rooms_grp','n_CURRENT_ENERGY_EFFICIENCY','n_ENVIRONMENT_IMPACT_CURRENT',
          'n_builtForm','PROPERTY_TYPE','n_tenure')

big_Dt_CSsubset_N6M7 <- big_Dt_CSsubset_N6M7[!is.na(TOTAL_FLOOR_AREA),]
vis_subset_N16M7 <- big_Dt_CSsubset_N6M7[ ,..cols]


#facetgrid: tenure x property type, region
  ggplot(vis_subset_N16M7[!is.na(n_habitable_rooms_grp),], aes(x = n_ENVIRONMENT_IMPACT_CURRENT, colour = n_habitable_rooms_grp)) +
  #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
  stat_density(lwd = 1, linetype = 1, position="identity",geom="line", bw = 2)+
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.3)+
  geom_vline( xintercept =  c(69,81), colour = 'black', size=.3)+
  #annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_colour_viridis_d(option = "plasma", direction	= -1)+ 
  scale_x_continuous(name = 'Current Environmental Impact' , breaks= lettermapping$cutoff)+
  facet_grid(rows = vars(n_tenure))


#facetgrid: tenure x property type, region
  ggplot(vis_subset_N16M7[!is.na(n_habitable_rooms_grp),], aes(x = n_ENVIRONMENT_IMPACT_CURRENT, colour = n_habitable_rooms_grp)) +
  #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
  stat_density(lwd = 1, linetype = 1, position="identity",geom="line", bw = 2)+
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.3)+
  geom_vline( xintercept =  c(69,81), colour = 'black', size=.3)+
  #annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_colour_viridis_d(option = "plasma", direction	= -1)+ 
  scale_x_continuous(name = 'Current Environmental Impact' , breaks= lettermapping$cutoff)+
  facet_grid(rows = vars(n_builtForm),vars(n_tenure))

```


```{r CEE addingInTenureBF}
cols <- c('TOTAL_FLOOR_AREA','NUMBER_HEATED_ROOMS','NUMBER_HABITABLE_ROOMS',
          'n_habitable_rooms_grp','n_CURRENT_ENERGY_EFFICIENCY','n_ENVIRONMENT_IMPACT_CURRENT',
          'n_builtForm','PROPERTY_TYPE','n_tenure')

big_Dt_CSsubset_N6M7 <- big_Dt_CSsubset_N6M7[!is.na(TOTAL_FLOOR_AREA),]
vis_subset_N16M7 <- big_Dt_CSsubset_N6M7[ ,..cols]

#facetgrid: tenure x property type, region
  ggplot(vis_subset_N16M7[!is.na(n_habitable_rooms_grp),], aes(x = n_CURRENT_ENERGY_EFFICIENCY, colour = n_habitable_rooms_grp)) +
  #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
  stat_density(lwd = 1, linetype = 1, position="identity",geom="line", bw = 2)+
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.3)+
  geom_vline( xintercept =  c(69,81), colour = 'black', size=.3)+
  #annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_colour_viridis_d(option = "plasma", direction	= -1)+ 
  scale_x_continuous(name = 'Current Environmental Efficiency' , breaks= lettermapping$cutoff)+
  facet_grid(rows = vars(n_tenure))






#facetgrid: tenure x property type, region
  ggplot(vis_subset_N16M7[!is.na(n_habitable_rooms_grp),], aes(x = n_CURRENT_ENERGY_EFFICIENCY, colour = n_habitable_rooms_grp)) +
  #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
  stat_density(lwd = 1, linetype = 1, position="identity",geom="line", bw = 2)+
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.3)+
  geom_vline( xintercept =  c(69,81), colour = 'black', size=.3)+
  #annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_colour_viridis_d(option = "plasma", direction	= -1)+ 
  scale_x_continuous(name = 'Current Environmental Impact' , breaks= lettermapping$cutoff)+
  facet_grid(rows = vars(n_builtForm),vars(n_tenure))

```



```{r CEI addingInTenure BF2}

#facetgrid: tenure x property type, region
  ggplot(vis_subset_N16M7[!is.na(n_habitable_rooms_grp),], aes(x = n_ENVIRONMENT_IMPACT_CURRENT, colour = n_habitable_rooms_grp)) +
  #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
  stat_density(lwd = 1, linetype = 1, position="identity",geom="line", bw = 2)+
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.3)+
  geom_vline( xintercept =  c(69,81), colour = 'black', size=.3)+
  #annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')+
  scale_colour_viridis_d(option = "plasma", direction	= -1)+ 
  scale_x_continuous(name = 'Current Environmental Impact' , breaks= lettermapping$cutoff)+
  facet_grid(rows = vars(PROPERTY_TYPE),vars(n_tenure))

```









```{r C02 per floor area 95th }
#Check CO2 emissions per floor area , by tenure and deprivation 

subset_P95 <- big_Dt_CSsubset_N6M7[!is.na(CO2_EMISS_CURR_PER_FLOOR_AREA)& 
CO2_EMISS_CURR_PER_FLOOR_AREA <= quantile(vis_subset_N16M7$TOTAL_FLOOR_AREA, 0.95, na.rm = T) & 
CO2_EMISS_CURR_PER_FLOOR_AREA >= quantile(vis_subset_N16M7$TOTAL_FLOOR_AREA, 0.05, na.rm = T)
,]

ggplot(subset_P95, aes(x = CO2_EMISS_CURR_PER_FLOOR_AREA, colour = n_habitable_rooms_grp)) +
    #geom_density(lwd = 1.2, linetype = 1, position="identity",geom="line", bw = 2)+  
    stat_density(lwd = 1, linetype = 1, position="identity",geom="line", bw = 2)+
    geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.3)+
    geom_vline( xintercept =  c(69,81), colour = 'black', size=.3)+
    #annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
    theme_minimal()+
    theme(legend.position = 'bottom', legend.box = 'horizontal')+
    scale_colour_viridis_d(option = "plasma", direction	= -1)+ 
    scale_x_continuous( breaks= lettermapping$cutoff)+
    facet_grid(rows = vars(n_tenure))
```






