---
title: "P3_CrossSectional_EDA"
author: "Boyana Buyuklieva"
date: "August 30, 2022"
output: html_document
---

#might need to clean up the construction age band of over 2007

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(data.table)
library(readxl)
library(readr)

loadRData <- function(fileName){
    #loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}

#get folders
cross_data <- list.files(path = "../Data/RData_crossSectional", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

cross_data <- gsub(".RData","",as.character(cross_data))
cross_data <- gsub("crossSectional_","",as.character(cross_data))

EDA_cols <- read_csv("../Data/EDA_colour_scheme.csv")
EDA_cols <- subset(EDA_cols[EDA_cols$geography_name %in%  cross_data, ])
```


```{r  aggregate by LSOA}
dt_LSOA <- data.table()
dt_LSOA_tenure <- data.table()

for (WIP in EDA_cols$geography_name) {
 if(WIP == "Unknown") break; 
 region_df <- loadRData(paste0("../Outputs/WIP_crossSectional/ONSUD_crossSectional_baseline_",WIP,".RData") ) 
 region_df$CURRENT_ENERGY_EFFICIENCY <- as.numeric(region_df$CURRENT_ENERGY_EFFICIENCY)
 
 
 dt_LSOA_row <- region_df[,by = c('lsoa11cd','lad19cd','rgn17cd'),
                  .(
                    n_lsoaCount_raw = .N,
                    n_lsoaMedian_CEE = median(CURRENT_ENERGY_EFFICIENCY),
                    n_lsoaVar_CEE = var(CURRENT_ENERGY_EFFICIENCY),
                    n_lsoaMedian_PEE = median(POTENTIAL_ENERGY_EFFICIENCY),
                    n_lsoaVar_PEE = var(POTENTIAL_ENERGY_EFFICIENCY)
                    )]
 
 dt_LSOA <- rbindlist( list(dt_LSOA, dt_LSOA_row)  )


 dt_LSOA_tenure_row <- region_df[,by = c('lsoa11cd','lad19cd','rgn17cd','n_tenure'),
                  .(
                    n_lsoaCount_raw = .N,
                    n_lsoaMedian_CEE = median(CURRENT_ENERGY_EFFICIENCY),
                    n_lsoaVar_CEE = var(CURRENT_ENERGY_EFFICIENCY),
                    n_lsoaMedian_PEE = median(POTENTIAL_ENERGY_EFFICIENCY),
                    n_lsoaVar_PEE = var(POTENTIAL_ENERGY_EFFICIENCY)
                    )]
 
 dt_LSOA_tenure <- rbindlist( list(dt_LSOA_tenure, dt_LSOA_tenure_row)  )
 
 print(WIP)
}
#expecting 32,844 lsoas







# add the IMDs
#includes England Only
imd2019lsoa <- fread("../Data/imd2019lsoa/imd2019lsoa.csv",
                     drop="Units", #empty column anyway
                     colClasses = c( "FeatureCode" = "character",
                                     "Measurement" = "character",
                                     "Value" = "numeric",
                                     "Indices of Deprivation" = "character"))


imd_bincome_rank <- imd2019lsoa[ `Indices of Deprivation`== 'b. Income Deprivation Domain',]
imd_bincome <-dcast(imd_bincome_rank, FeatureCode ~ Measurement, value.var = c("Value"))
imd_bincome$lsoaKey <- imd_bincome$FeatureCode
setkey(imd_bincome, lsoaKey)

dt_LSOA$lsoaKey <- dt_LSOA$lsoa11cd
setkey(dt_LSOA, lsoaKey)

#note: this misses the Welsch income deprivations
LSOA_imdEPC <- imd_bincome[dt_LSOA, on = 'lsoaKey']

#do an quantile rank
LSOA_imdEPC[ , n_lsoaMedian_CEE_rank := cut(n_lsoaMedian_CEE,
                            breaks=quantile(n_lsoaMedian_CEE,
                            probs=seq(0, 1, by=0.1), na.rm=T),
                            include.lowest= TRUE, labels=1:10) ]


lettermapping <-  data.frame( letter = c('A','B','C','D','E','F','G'), 
                              cutoff = c(92, 81, 69, 55, 39, 21, 0))
#do an quantile rank
LSOA_imdEPC[ , n_lsoaMedian_CEE_Crel := cut(n_lsoaMedian_CEE,
                            breaks = c(0, 68, 80, Inf),
                            include.lowest= TRUE, labels=c('belowC','C','aboveC')) ]

#do an quantile rank
LSOA_imdEPC[ , DecileGrps := cut(Decile,
                            breaks = c(0, 3, 7, Inf),
                            include.lowest= TRUE, labels=c('Decile_1-3_deprived','Decile_4-7','Decile_8-10')) ]
```

```{r}
LSOA_imdEPC$lsoaKey <- NULL
LSOA_imdEPC$bivariateIncomeIMD_EPCV10 <- paste0(LSOA_imdEPC$DecileGrps,"-", LSOA_imdEPC$n_lsoaMedian_CEE_Crel)
write.csv(LSOA_imdEPC,'../Outputs/LSOA_imdEPC.csv')

dt_LSOA_tenure$lsoaKey <- NULL
write.csv(dt_LSOA_tenure,'../Outputs/LSOA_tenure_EPCs.csv')
```



```{r quickSanityCheck}
underC <- LSOA_imdEPC[ n_lsoaCount_raw > 5 & n_lsoaMedian_CEE < 69,]

#fit regression model
fit <- lm( n_lsoaMedian_CEE ~ Rank, data=underC)

#create scatter plot
plot(n_lsoaMedian_CEE ~ Rank, data=underC)

#add fitted regression line to scatterplot
abline(fit, col = 'red')
#more affluent places are have slightly lower EPC scores. 
```







