---
title: "P3_CrossSectional_EDA"
author: "Boyana Buyuklieva"
date: "August 30, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(data.table)
library(readxl)
library(readr)

loadRData <- function(fileName){
    #loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}

#get folders
cross_data <- list.files(path = "../Data/RData_crossSectional", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

cross_data <- gsub(".RData","",as.character(cross_data))
cross_data <- gsub("crossSectional_","",as.character(cross_data))

EDA_cols <- read_csv("../Data/EDA_colour_scheme.csv")
EDA_cols <- subset(EDA_cols[EDA_cols$geography_name %in%  cross_data, ])

#formatting:
lettermapping <-  data.frame( letter = c('A','B','C','D','E','F','G'), 
                              cutoff = c(92, 81, 69, 55, 39, 21, 0))
```

```{r}
big_Dt <- data.table()
for (WIP in EDA_cols$geography_name) {
 if(WIP == "Unknown") break; 
 region_df <- loadRData(paste0("../Outputs/WIP_crossSectional/ONSUD_crossSectional_baseline_",WIP,".RData") ) 
 region_df$CURRENT_ENERGY_EFFICIENCY <- as.numeric(region_df$CURRENT_ENERGY_EFFICIENCY)
 region_df$regionName
 big_Dt <- rbindlist(list(big_Dt,region_df))
}


#resolve age:
big_Dt <- big_Dt[, nn_construction_age_band := n_construction_age_band]
big_Dt <- big_Dt[n_construction_age_band == '2012 onwards' | n_construction_age_band =='2007-2011', nn_construction_age_band := '2007 onwards']
big_Dt <- big_Dt[n_construction_age_band == 'Not applicable', nn_construction_age_band := 'unknown']
fctr_levels <- c("Pre-1900","1900-1929","1930-1949","1950-1966","1967-1975","1976-1982","1983-1990","1991-1995","1996-2002","2003-2006","2007 onwards","unknown")
big_Dt <- big_Dt[,setattr(nn_construction_age_band,'levels',fctr_levels)]
```

```{r resolving building age}

col <- c("TRANSACTION_TYPE","INSPECTION_DATE")
dt2007_onward <-  big_Dt[ nn_construction_age_band == '2007 onwards', ..col]
dt2007_onward_n <- dt2007_onward[, by = "TRANSACTION_TYPE", .(n = .N)]


dt2007_onward <- dt2007_onward[ n_construction_age := year(dt2007_onward$INSPECTION_DATE) ]


# Stacked + percent
plot_dt <- big_Dt[ , by = 'nn_construction_age_band',
                   .(n = .N)]
plot_dt$percent <- round(plot_dt$n/sum(plot_dt$n),3)

ggplot(plot_dt, aes(fill=nn_construction_age_band, x= "", y=n)) + 
  geom_bar(position="fill", stat="identity")+ 
  coord_flip()+theme(axis.text.y=element_blank())


plot_dt <- plot_dt[order(plot_dt$nn_construction_age_band),]
plot_dt <- plot_dt[c(11, seq(1,10,1),12),]
plot_dt[,setattr(nn_construction_age_band,'levels',c(plot_dt$nn_construction_age_band))]


ggplot(plot_dt, aes(x=nn_construction_age_band, y=n))+ 
  geom_bar(stat='identity')+ 
  coord_flip()

+theme(axis.text.y=element_blank())
```


```{r}
sample <-big_Dt[sample( x= nrow(big_Dt), size = 9000, replace = F),] 
```

```{r}
ggplot(sample, aes(x = CURRENT_ENERGY_EFFICIENCY, colour = n_construction_age_band)) +
  geom_density(lwd = 1.2, linetype = 1)



+ 
  scale_color_manual(values = EDA_cols$colour, 
                     labels = EDA_cols$geography_name)
```


```{r}
#PDP by building age
#facetgrid: tenure x building type, region
#facetgrid: tenure x built form, region

#Scatterplot: income deprivation rank by EPCs


```


















```{r}
regional_histo_plots <- list()
start.time <- Sys.time()

for (WIP in EDA_cols$geography_name) {
 if(WIP == "Unknown") break; 
 region_df <- loadRData(paste0("../Outputs/WIP_crossSectional/ONSUD_crossSectional_baseline_",WIP,".RData") ) 
 region_df$CURRENT_ENERGY_EFFICIENCY <- as.numeric(region_df$CURRENT_ENERGY_EFFICIENCY)
 print(paste(WIP, Sys.time()))
  
  #Plot prep
  ##set all the values that are over 100 to 101, EPCs aren't bound to 100 
  region_df[CURRENT_ENERGY_EFFICIENCY > 101]$CURRENT_ENERGY_EFFICIENCY <- 101
  EDA_col <-  EDA_cols$colour[which(EDA_cols$geography_name %in% WIP)]
  
  
  regional_histo_plots[[WIP]] <-   geom_histogram(data = region_df, 
                              aes(CURRENT_ENERGY_EFFICIENCY , fill = I(EDA_col), alpha=0.5 ),
                              binwidth = 1)
  
  
}

print(paste('loop time:', Sys.time() - start.time))#plot loop takes 40mins



#formatting:
lettermapping <-  data.frame( letter = c('A','B','C','D','E','F','G'), 
                              cutoff = c(92, 81, 69, 55, 39, 21, 0))
  

plot_obj <-  ggplot() + regional_histo_plots$`East Midlands`
plot_obj <-  ggplot() + regional_histo_plots$`East of England`


+ regional_histo_plots[[2]]

plot_obj + 
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=.6)+ 
  annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  theme_classic() + theme(legend.position = 'bottom', legend.box = 'horizontal')



```







```{r}
ggplot() + geom_histogram(data = region_df, 
                              #aes_string('CURRENT_ENERGY_EFFICIENCY', colour = EDA_col),
                              aes(CURRENT_ENERGY_EFFICIENCY , colour = n_tenure, fill = I(EDA_col), alpha=0.5 ),
                              binwidth = 1)
    
    ggplot() + geom_histogram(data = region_df, 
                              #aes_string('CURRENT_ENERGY_EFFICIENCY', colour = EDA_col),
                              aes(CURRENT_ENERGY_EFFICIENCY , colour = n_builtForm, fill = I(EDA_col), alpha=0.5 ),
                              binwidth = 1)
    
        
    ggplot() + geom_density(data = region_df, 
                              #aes_string('CURRENT_ENERGY_EFFICIENCY', colour = EDA_col),
                              aes(CURRENT_ENERGY_EFFICIENCY , colour = n_builtForm, fill = I(EDA_col), alpha=0.5) )
```




```{r testing_sample}
region <- cross_data[4]

region_df<- loadRData( paste0("../Outputs/WIP_crossSectional/crossSectional_baseline_",region,".RData") )


tmp_region_df <- head(region_df, 200)
  

ggplot() + geom_density(data = tail(region_df, 100), 
                        aes(CURRENT_ENERGY_EFFICIENCY, by = n_tenure, colour = n_tenure),
                        cut(0,100))



library(scales) # For percent_format()

ggplot(tail(region_df, 100), aes(CURRENT_ENERGY_EFFICIENCY, fill=n_tenure, colour=n_tenure)) +
  geom_histogram(aes(y=2*(..density..)/sum(..density..)), breaks=seq(0,100,1), alpha=0.6, 
                 position="identity", lwd=0.2) +
  scale_y_continuous(labels=percent_format())



```

```{r density_plot}
#set all the values that are over 100 to 101, EPCs aren't bound to 100 
plot_obj <-  ggplot(tmp_region_df) +
             geom_density(aes(CURRENT_ENERGY_EFFICIENCY, colour = n_tenure))

```


```{r formatting}
#formatting:
lettermapping <-  data.frame( letter = c('A','B','C','D','E','F','G'), 
                              cutoff = c(92, 81, 69, 55, 39, 21, 1))
  
plot_obj + 
  geom_vline( xintercept =  lettermapping$cutoff, colour = 'grey', size=1)+ 
  annotate("text",x = lettermapping$cutoff+5, y= 0.1, label=lettermapping$letter, angle=90, size=5)+
  theme_classic() + theme(legend.position = 'bottom', legend.box = 'horizontal')

```



```{r ordered_scater}
#CEE - Usage variable   
#environmental impact rating. 
#potential vs current 
```

