---
title: "P3_CrossSectional_EDA"
author: "Boyana Buyuklieva"
date: "August 30, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache.lazy = FALSE)
library(dplyr)
library(tidyverse)
library(data.table)
library(readr)
library(foreign)
library(ggExtra)
library(gridExtra)

loadRData <- function(fileName){
    #loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}

#formatting:
lettermapping <-  data.frame( letter = c('A','B','C','D','E','F','G'), 
                              cutoff = c(92, 81, 69, 55, 39, 21, 0))



big_Dt_CSsubset_N6M7 <- loadRData("../Outputs/WIP_crossSectional/ONSUD_crossSectional_subset_N16744771.RData")

#Formatting n_Crel:
fctr_levels <- c("C+","C","C-")
big_Dt_CSsubset_N6M7[,n_Crel := factor(n_Crel, levels = fctr_levels, ordered = T)]
#Formatting NUMBER_HABITABLE_ROOMS:
#tally <- big_Dt_CSsubset_N6M7[, .(n = .N) ,by=NUMBER_HABITABLE_ROOMS ]
big_Dt_CSsubset_N6M7[, NUMBER_HABITABLE_ROOMS:=as.integer(NUMBER_HABITABLE_ROOMS)]



###IMD:LOAD DATA
#multiple deprivation EW
IMD19<- read.dbf("../Data/_shapefiles/Lower_Super_Output_Area_(LSOA)_IMD_2019__(OSGB1936)/Lower_Super_Output_Area_(LSOA)_IMD_2019__(OSGB1936).dbf")

#income deprivation E
income_imd2019lsoa_E <- fread("../Data/imd2019lsoa/imd2019lsoa.csv",
                     drop="Units", #empty column anyway
                     colClasses = c( "FeatureCode" = "character",
                                     "Measurement" = "character",
                                     "Value" = "numeric",
                                     "Indices of Deprivation" = "character"))

#Measurements are: "Rank"   "Decile" "Score"
#income_imd2019lsoa_E <- setNames(income_imd2019lsoa_E, c("lsoa11cd","Date","Measurement","Value","Indices of Deprivation") )
setnames(income_imd2019lsoa_E, c("FeatureCode"), c("lsoa11cd"))

EDA_cols <- read_csv("../Data/EDA_colour_scheme.csv")
#EDA_cols <- subset(EDA_cols[EDA_cols$geography_name %in%  cross_data, ])
```

```{r attach_IMDs}
##ATTACH DATA 
big_Dt_CSsubset_N6M7[IMD19,  on = 'lsoa11cd', c('n_IMDRank','n_IMDDecil') := .(IMDRank,IMDDecil)]

#Add IoD
##can select other IoD here
imd_bincome <-  income_imd2019lsoa_E[ `Indices of Deprivation` == "b. Income Deprivation Domain",]
imd_bincome <-dcast(imd_bincome, lsoa11cd ~ Measurement, value.var = c("Value"))
big_Dt_CSsubset_N6M7[imd_bincome,  on = 'lsoa11cd', c('n_bIoDRank_income','n_bIoDDecil_income') := .(Rank,Decile)]

```
 
```{r extreme_values_treatment}
#Edit 1: CEE values over 100 are set to 101
big_Dt_CSsubset_N6M7[, n_CURRENT_ENERGY_EFFICIENCY := ifelse( CURRENT_ENERGY_EFFICIENCY>100 ,101, CURRENT_ENERGY_EFFICIENCY)]
big_Dt_CSsubset_N6M7[, n_POTENTIAL_ENERGY_EFFICIENCY := ifelse( POTENTIAL_ENERGY_EFFICIENCY>100 ,101, POTENTIAL_ENERGY_EFFICIENCY)]

#Edit 2: EIC values over 100 are set to 101
big_Dt_CSsubset_N6M7[, n_ENVIRONMENT_IMPACT_CURRENT := ifelse( ENVIRONMENT_IMPACT_CURRENT>100 ,101, ENVIRONMENT_IMPACT_CURRENT)]
big_Dt_CSsubset_N6M7[, n_ENVIRONMENT_IMPACT_POTENTIAL := ifelse( ENVIRONMENT_IMPACT_POTENTIAL>100 ,101, ENVIRONMENT_IMPACT_POTENTIAL)]

#Edit 3: Places with over 7 habitable rooms are grouped together into 7+
fctr_levels <- c(paste0(seq(1,6,1), 'HaR'), '+7HaR' )
big_Dt_CSsubset_N6M7[ , n_habitable_rooms_grp := ifelse( NUMBER_HABITABLE_ROOMS>6,'+7HaR', paste0(NUMBER_HABITABLE_ROOMS,'HaR'))]
big_Dt_CSsubset_N6M7[ , n_habitable_rooms_grp := factor(n_habitable_rooms_grp, levels = fctr_levels, ordered = T)]

#Edit 4: Places with over 9 heated rooms are grouped together into 8+
fctr_levels <- c(paste0(seq(1,8,1), 'HtR'), '+9HtR' )
big_Dt_CSsubset_N6M7[ , n_heated_rooms_grp := ifelse( NUMBER_HEATED_ROOMS>8,'+8HtR', paste0(NUMBER_HEATED_ROOMS,'HtR'))]
big_Dt_CSsubset_N6M7[ , n_heated_rooms_grp := factor(n_heated_rooms_grp, levels = fctr_levels, ordered = T)]

#Edit 5: Floor Area. 
#Note min bedroom size is 6.5m2 = 7m2
#Max is 270, based on the 99 percentile of the entries
maxthreshold <- round(quantile(big_Dt_CSsubset_N6M7$TOTAL_FLOOR_AREA, 0.99, na.rm = T),0)
print(paste('The 99 percentile of floor area is: ', maxthreshold, 'm2'))
big_Dt_CSsubset_N6M7[, n_TOTAL_FLOOR_AREA  := ifelse( TOTAL_FLOOR_AREA < 6 ,6, n_TOTAL_FLOOR_AREA)]
big_Dt_CSsubset_N6M7[, n_TOTAL_FLOOR_AREA  := ifelse( TOTAL_FLOOR_AREA > maxthreshold , maxthreshold+1, n_TOTAL_FLOOR_AREA)]


#Edit 6:
big_Dt_CSsubset_N6M7[ , n_bIoDDecil_income_grp := cut(n_bIoDDecil_income,
                            breaks = c(0, 3, 7, Inf),
                            include.lowest= TRUE, labels=c('IncomeDeprived_1-3','AverageIncome_4-7','IncomeUnDeprived_8-10')) ]
```

```{r extreme_values_treatment}
#Edited Variable 1: Potential Change PEE 
big_Dt_CSsubset_N6M7[, nn_potEE := n_POTENTIAL_ENERGY_EFFICIENCY - n_CURRENT_ENERGY_EFFICIENCY]
#Edited Variable 2: Potential Change EIP 
big_Dt_CSsubset_N6M7[, nn_potIE := n_ENVIRONMENT_IMPACT_POTENTIAL - n_ENVIRONMENT_IMPACT_CURRENT]

#Edited Variable 3: Combine all terraced housing
big_Dt_CSsubset_N6M7[, nn_builtForm := n_builtForm]
big_Dt_CSsubset_N6M7[, nn_builtForm := ifelse( nn_builtForm == 'Mid-Terrace', 'Terrace', nn_builtForm)]
big_Dt_CSsubset_N6M7[, nn_builtForm := ifelse( nn_builtForm == 'End-Terrace', 'Terrace', nn_builtForm)]

#Might need doing: big_Dt_CSsubset_N6M7[, nn_CO2_EMISS_CURR_PER_FLOOR_AREA := round(CO2_EMISSIONS_CURRENT/n_TOTAL_FLOOR_AREA,0) ]
#would need to add the raw data
```

```{subsetting r}
#big_Dt_CSsubset_N6M7 <- big_Dt_CSsubset_N6M7[!is.na(TOTAL_FLOOR_AREA),]
```



```{r visTest}
dt <- big_Dt_CSsubset_N6M7[ sample(nrow(big_Dt_CSsubset_N6M7), 300),]

#add colour by letter difference. 


raw <- ggplot(dt, aes(CURRENT_ENERGY_EFFICIENCY, ENVIRONMENT_IMPACT_CURRENT))+
  geom_point()+ #geom_point(aes(color = n_Crel))
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')
  
ggMarginal(raw, type="density")





dt[ , n_CEE_rating := cut(n_bIoDDecil_income,
                            breaks = c(0, 3, 7, Inf),
                            include.lowest= TRUE, labels=c('IncomeDeprived_1-3','AverageIncome_4-7','IncomeUnDeprived_8-10')) ]


edited <- ggplot(dt, aes(n_CURRENT_ENERGY_EFFICIENCY, n_ENVIRONMENT_IMPACT_CURRENT))+
  geom_point()+ #geom_point(aes(color = n_Crel))
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')


ggMarginal(edited, type="density")
```












```{r makingdata_smaller}
cols <- c('TOTAL_FLOOR_AREA','NUMBER_HEATED_ROOMS','NUMBER_HABITABLE_ROOMS',
          'n_habitable_rooms_grp','n_CURRENT_ENERGY_EFFICIENCY','n_ENVIRONMENT_IMPACT_CURRENT',
          'n_builtForm','PROPERTY_TYPE','n_tenure','n_bIoDDecil_income_grp', 'n_Crel','CO2_EMISS_CURR_PER_FLOOR_AREA')

vis_subset_N16M7 <- big_Dt_CSsubset_N6M7[ ,..cols]
```


```{r actual}
raw <- ggplot(big_Dt_CSsubset_N6M7, aes(CURRENT_ENERGY_EFFICIENCY, ENVIRONMENT_IMPACT_CURRENT))+
  geom_point()+ #geom_point(aes(color = n_Crel))
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')
  
ggMarginal(raw, type="density")


edited <- ggplot(big_Dt_CSsubset_N6M7, aes(n_CURRENT_ENERGY_EFFICIENCY, n_ENVIRONMENT_IMPACT_CURRENT))+
  geom_point()+ #geom_point(aes(color = n_Crel))
  theme_minimal()+
  theme(legend.position = 'bottom', legend.box = 'horizontal')


ggMarginal(edited, type="density")
```











