---
title: "Tenure - EPCs in V10"
author: "Boyana Buyuklieva"
date: "May 4, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
#library(DescTools)

library(dplyr)
library(tidyr)
```



```{r path}
WIP_tenure_LUT <- read_csv("../Outputs/WIP_tenure_LUT.csv")

#get folders
folders <- list.files(path = "../Data/all-domestic-certificates", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

folders <- folders[-342] #remove the .txt
```

```{metadataCross r}
#setup Metadata Folders 
#Get difference by LAD, eg.g: 
folders_meta <- data.frame(names = folders)
folders_meta$folder <- folders
folders_meta$region <- ''

folders_meta$totalEntries <- 0
folders_meta$totalwithoutUPRN <- 0
folders_meta$totalwithoutLodgementDate <- 0



## Min, Max, Mean, SD of INSPECTION DATE and/or Lodgementdate
folders_meta$IdateMin <- 0
folders_meta$IdateMax <- 0
folders_meta$IdateMedian <- 0 #Problem NAs
  
folders_meta$LdateMin <- 0
folders_meta$LdateMax <- 0
folders_meta$LdateMedian <- 0 #Problem NAs


## CURRENT_ENERGY_RATING (factor)
folders_meta$cERmedian <- 0
folders_meta$PerCentcER_underC <- 0


## POTENTIAL - CURRENT_ENERGY_EFFICIENCY (int)
folders_meta$p_cEEficMedian <- 0 #Problem NAs
folders_meta$p_cEEficMean <- 0
folders_meta$p_cEEficSD <- 0




##from the longitudinal
folders_meta$PerCentOneOffEntries <- 0 ## % one-off entries by folder.
```

```{r loop}
C_relative <- data.frame(matrix(ncol = 4, nrow = 0))
names(C_relative) <- c('m_TENURE', 'm_Crel', 'n', 'LA')


for (f in folders) {
  print(f)
  LA <- f
  certificates <- read_csv(paste0("../Data/all-domestic-certificates/",LA,"/certificates.csv"), 
    col_types = cols(COUNTY = col_character(), MAIN_HEATING_CONTROLS = col_character(),
        INSPECTION_DATE = col_date(format = "%Y-%m-%d"), 
        LMK_KEY = col_character(), LODGEMENT_DATE = col_date(format = "%Y-%m-%d"), 
        LODGEMENT_DATETIME = col_character()))
  #LODGEMENT_DATETIME = col_character() because it sometimes includes H:M:S
  
  certificates$m_TENURE <- WIP_tenure_LUT$Harmonised[match(unlist(certificates$TENURE), WIP_tenure_LUT$Database)]
  
  certificates$m_Crel <- ifelse(certificates$CURRENT_ENERGY_RATING == 'C', 'C', 
                                ifelse(certificates$CURRENT_ENERGY_RATING %in% c('A', 'B'), 'C+', 
                                       ifelse(certificates$CURRENT_ENERGY_RATING %in% c('D', 'E','F','G'),'C-','NA' )))
  
  #make as factor
  certificates$m_Crel <- factor(certificates$m_Crel, levels = c('C+','C','C-'))
  certificates$m_TENURE <- factor(certificates$m_TENURE, levels = unique(WIP_tenure_LUT$Harmonised))

  rows <- certificates %>% 
  group_by(m_TENURE,m_Crel, .drop = FALSE) %>% 
  summarise(n=n(),
            folder = LA)

C_relative <- rbind(C_relative, as.data.frame(rows))
  
}


write.csv(C_relative, file = "../Outputs/WIP_c_relative_tenure.csv")
```



