---
title: "P3_CrossSectional_EDA"
author: "Boyana Buyuklieva"
date: "August 30, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache.lazy = FALSE)
library(dplyr)
library(tidyverse)
library(data.table)
library(readr)
library(foreign)
library(ggExtra)
library(gridExtra)


loadRData <- function(fileName){
    #loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}

big_Dt_CSsubset_N6M7 <- loadRData("../Outputs/WIP_crossSectional/ONSUD_crossSectional_subset_N16744771.RData")
fctr_levels <- c("C+","C","C-")
big_Dt_CSsubset_N6M7[,n_Crel := factor(n_Crel, levels = fctr_levels, ordered = T)]

#tally <- big_Dt_CSsubset_N6M7[, .(n = .N) ,by=NUMBER_HABITABLE_ROOMS ]
big_Dt_CSsubset_N6M7[, NUMBER_HABITABLE_ROOMS:=as.integer(NUMBER_HABITABLE_ROOMS)]

fctr_levels <- c(paste0(seq(1,6,1), 'HR'), '+7HR' )
big_Dt_CSsubset_N6M7[ , n_habitable_rooms_grp := ifelse( NUMBER_HABITABLE_ROOMS>6,'+7HR', paste0(NUMBER_HABITABLE_ROOMS,'HR'))]
big_Dt_CSsubset_N6M7[,n_habitable_rooms_grp := factor(n_habitable_rooms_grp, levels = fctr_levels, ordered = T)]



big_Dt_CSsubset_N6M7[, n_CURRENT_ENERGY_EFFICIENCY := ifelse( CURRENT_ENERGY_EFFICIENCY>100 ,101, CURRENT_ENERGY_EFFICIENCY)]
big_Dt_CSsubset_N6M7[, n_POTENTIAL_ENERGY_EFFICIENCY := ifelse( POTENTIAL_ENERGY_EFFICIENCY>100 ,101, POTENTIAL_ENERGY_EFFICIENCY)]

big_Dt_CSsubset_N6M7[, n_ENVIRONMENT_IMPACT_CURRENT := ifelse( ENVIRONMENT_IMPACT_CURRENT>100 ,101, ENVIRONMENT_IMPACT_CURRENT)]
big_Dt_CSsubset_N6M7[, n_ENVIRONMENT_IMPACT_POTENTIAL := ifelse( ENVIRONMENT_IMPACT_POTENTIAL>100 ,101, ENVIRONMENT_IMPACT_POTENTIAL)]


big_Dt_CSsubset_N6M7[, n_potEE := n_POTENTIAL_ENERGY_EFFICIENCY - n_CURRENT_ENERGY_EFFICIENCY]
big_Dt_CSsubset_N6M7[, n_potIE := n_ENVIRONMENT_IMPACT_POTENTIAL - n_ENVIRONMENT_IMPACT_CURRENT]

#formatting:
lettermapping <-  data.frame( letter = c('A','B','C','D','E','F','G'), 
                              cutoff = c(92, 81, 69, 55, 39, 21, 0))

```



#from P3a_CS_Big_Dt
```{r IMD IoDb comparison}
#How does IMD compare to Income ID in England Only?
##Scatter plot

#ggplot(tmp[!is.na(n_bIoDRank_income), ],
ggplot(big_Dt_CSsubset_N6M7[!is.na(n_bIoDRank_income), ],
       aes(x=n_IMDRank, y=n_bIoDRank_income, color=n_Crel)) +
  geom_point(alpha = 1/10) + 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)+
  scale_colour_manual(values = c("C+" = "#ffa600", "C" = "#808080", "C-" = "#008cff"))


if(F){
model_Cplus <- lm(n_IMDRank ~ n_bIoDRank_income, 
            data = big_Dt_CSsubset_N6M7[!is.na(n_bIoDRank_income) & n_Crel=="C+", ])
summary(model_Cplus)

model_Cminus <- lm(n_IMDRank ~ n_bIoDRank_income, 
            data = big_Dt_CSsubset_N6M7[!is.na(n_bIoDRank_income) & n_Crel=="C-", ])
summary(model_Cminus)

model_C <- lm(n_IMDRank ~ n_bIoDRank_income, 
            data = big_Dt_CSsubset_N6M7[!is.na(n_bIoDRank_income) & n_Crel=="C", ])
summary(model_C) 
}
```

```{r CEE and EIC relationship}
#https://r-graph-gallery.com/277-marginal-histogram-for-ggplot2.html
#ggplot(tmp,
ggplot(big_Dt_CSsubset_N6M7[ ENVIRONMENT_IMPACT_CURRENT<101],
       aes(x=nn_CURRENT_ENERGY_EFFICIENCY, y=ENVIRONMENT_IMPACT_CURRENT, color=n_Crel)) +
  geom_point(alpha = 1/10) + 
  geom_smooth(method=lm, 
              se=FALSE, 
              fullrange=F)+
  scale_colour_manual(
    values = c("C+" = "#ffa600", "C" = "#808080", "C-" = "#008cff"))
```


















