---
title: "Duplicate (strings) EPCs in V10"
author: "Boyana Buyuklieva"
date: "May 12, 2022"
output: html_document
---

#This version is has quadratic time complexity. Est runtime 3 months

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load(file = './MetaData&StringDups.RData')
```


[Information on how the Energy Rating map to Energy Efficiency](https://www.edfenergy.com/energy-efficiency/how-improve-your-epc-rating)

```{r}
#Df of all rows that repeat
tmp <- str_dups
  
#flag fist entries   
tmp$firstEntry <- F
firstEntry <-which(!duplicated(tmp$combined)) #3539058
tmp$firstEntry[firstEntry] <- T 
rm(firstEntry)


#set up the time column, relative to Inspection Date
tmp$n_deltaDays <-  0

#Delta(ER)
#might cause problems without trimming white spaces and caps
tmp$n_dER <- as.numeric(factor(tmp$CURRENT_ENERGY_RATING, 
                       ordered = T, levels = c('A','B','C','D','E','F')))
tmp$n_dEE <- tmp$CURRENT_ENERGY_EFFICIENCY
```

```{r}
dupcol <- 'combined'
i = 0

uniqueRows <-  unique(tmp[,dupcol])


for (entry in uniqueRows ) {
  
  #print(which(entry == unique(tmp[,dupcol])))
  #get a case of duplicates
  tmp_entries <- subset(tmp, tmp[,dupcol] == entry)
  tmp_LMKs <- unique(tmp_entries$LMK_KEY)
  
  if(i %% 1000 == 0 ){print(paste0(i,' ', Sys.time() ) )}
  i = i+1
  
  for (row in length(tmp_LMKs)){
  if(row > 1){ #row one is always the first entry
    # tmp_entries$n_dER[row] <- tmp_entries$n_dER[1] - tmp_entries$n_dER[row] # factor as numbers
    # tmp_entries$n_dER[row] <- tmp_entries$CURRENT_ENERGY_EFFICIENCY[row] -tmp_entries$CURRENT_ENERGY_EFFICIENCY[1]
    # tmp_entries$n_deltaDays[row] <- as.numeric(difftime(tmp_entries$INSPECTION_DATE[row] ,tmp$INSPECTION_DATE[1] , units = c("days"))) 
    
    
    index <- which(tmp$LMK_KEY %in% tmp_LMKs[row])
    tmp$n_dER[index ]<- tmp_entries$n_dER[1] - tmp_entries$n_dER[row] # factor as numbers
    tmp$n_dEE[index ] <- tmp_entries$CURRENT_ENERGY_EFFICIENCY[row] -tmp_entries$CURRENT_ENERGY_EFFICIENCY[1]
    tmp$n_deltaDays[index ] <- as.numeric(difftime(tmp_entries$INSPECTION_DATE[row] ,tmp$INSPECTION_DATE[1] , units = c("days"))) 
   }
  }
}


str_dups_deltas <- tmp
save(str_dups_deltas, file = 'C:/Users/billi/Dropbox/_PhD/Application Documents/CASA RA/RA OS NARRATE CASA/Code/str_dups_deltas.RData' )
```

