---
title: "Tenure - EPCs in V10"
author: "Boyana Buyuklieva"
date: "May 4, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(data.table)
library(fasttime)
library(readxl)

loadRData <- function(fileName){
    #loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}

#get folders
cross_data <- list.files(path = "../Data/RData_crossSectional", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
cross_data <- gsub(".RData","",as.character(cross_data))
cross_data <- gsub("crossSectional_","",as.character(cross_data))


#get loopUp
LUT_tenure <- read_excel("../Data/OS-N_EPC_v10_LUT+dictionaries.xlsx", sheet = "TENURE",range = cell_cols("B:C"))
LUT_builtForm <- read_excel("../Data/OS-N_EPC_v10_LUT+dictionaries.xlsx", sheet = "BUILT_FORM",range = cell_cols("B:C"))
```


#Change based on LUT
```{r crossSectional_loop}

start.time <- Sys.time()
  
for (region in cross_data) {
  #region = cross_data[4] #testing
  print(paste(region, Sys.time()))
  
  tmp <- loadRData(paste0("../Data/RData_crossSectional/crossSectional_",region,".RData") )
  
  #CREATE NEW COLUMNS
  #N1: info on UPRNs differences and NAs
  tmp[, n_erNoUPRN := ifelse(UPRN == ubdc_UPRN,'same','diffUPRNs')]
  tmp[, n_erNoUPRN := ifelse(UPRN == "" | is.na(UPRN),'diffUPRNs_NA_UPRN',n_erNoUPRN) ]
  tmp[, n_erNoUPRN := ifelse(ubdc_UPRN == ""| is.na(ubdc_UPRN),'diffUPRNs_NA_ubdc_UPRN',n_erNoUPRN) ]
  tmp[, n_erNoUPRN := ifelse(n_UPRN == "" | is.na(n_UPRN),'noUPRN',n_erNoUPRN) ]

  
  #N2: create C relative column
  tmp[, n_Crel:= ifelse(CURRENT_ENERGY_RATING == 'C', 'C', 
                                ifelse(CURRENT_ENERGY_RATING %in% c('A', 'B'), 'C+', 
                                       ifelse(CURRENT_ENERGY_RATING %in% c('D', 'E','F','G'),'C-','NA' )))]
  #tmp[CURRENT_ENERGY_RATING =="INVALID!", ]$CURRENT_ENERGY_EFFICIENCY
  tmp[n_Crel =="NA", n_Crel:= ifelse(CURRENT_ENERGY_EFFICIENCY > 100, 'C+', 'C-')]
  
  
  #N3: create new Tenure column
  LUT_colum <- LUT_tenure[match(tmp$TENURE, LUT_tenure$tenure_factors),"harmonisation"]
  tmp[,n_tenure := LUT_colum]
  tmp[is.na(n_tenure),n_tenure := 'unknown'] #deals with NAs
      
  #N4: create new Built Form column
  LUT_colum <- LUT_builtForm[match(tmp$BUILT_FORM, LUT_builtForm$BUILT_FORMfactors),"harmonisation"]
  tmp[,n_builtForm := LUT_colum]
  tmp[is.na(n_builtForm),n_builtForm := 'unknown'] 
      

  
  tmp <- tmp[, c("LAD11NM","LMK_KEY","n_UPRN","n_erNoUPRN","CURRENT_ENERGY_EFFICIENCY","n_Crel", "n_tenure", "n_builtForm","TENURE","BUILT_FORM","PROPERTY_TYPE","POTENTIAL_ENERGY_EFFICIENCY","str_concat","UPRN","ubdc_UPRN")]
  save(tmp, file = paste0("../Outputs/WIP_crossSectional/crossSectional_baseline_",region,".RData") )
}

print(Sys.time()-start.time)
```


#Combine age bands in 2007 onwards
```{r subset_N16744771_resolving building age, include=FALSE}
if(F){
#from EDA Scratchpad
EDA_cols <- read_csv("../Data/EDA_colour_scheme.csv")
EDA_cols <- subset(EDA_cols[EDA_cols$geography_name %in%  cross_data, ])


big_Dt <- data.table()
for (WIP in EDA_cols$geography_name) {
 if(WIP == "Unknown") break; 
 region_df <- loadRData(paste0("../Outputs/WIP_crossSectional/ONSUD_crossSectional_baseline_",WIP,".RData") ) 
 region_df$CURRENT_ENERGY_EFFICIENCY <- as.numeric(region_df$CURRENT_ENERGY_EFFICIENCY)
 region_df$regionName
 big_Dt <- rbindlist(list(big_Dt,region_df))
}


col <- c("TRANSACTION_TYPE","INSPECTION_DATE")
dt2007_onward <-  big_Dt[ nn_construction_age_band == '2007 onwards', ..col]
dt2007_onward_n <- dt2007_onward[, by = "TRANSACTION_TYPE", .(n = .N)]


dt2007_onward <- dt2007_onward[ n_construction_age := year(dt2007_onward$INSPECTION_DATE) ]


# Stacked + percent
plot_dt <- big_Dt[ , by = 'nn_construction_age_band',
                   .(n = .N)]
plot_dt$percent <- round(plot_dt$n/sum(plot_dt$n),3)

ggplot(plot_dt, aes(fill=nn_construction_age_band, x= "", y=n)) + 
  geom_bar(position="fill", stat="identity")+ 
  coord_flip()+theme(axis.text.y=element_blank())


plot_dt <- plot_dt[order(plot_dt$nn_construction_age_band),]
plot_dt <- plot_dt[c(11, seq(1,10,1),12),]
plot_dt[,setattr(nn_construction_age_band,'levels',c(plot_dt$nn_construction_age_band))]


ggplot(plot_dt, aes(x=nn_construction_age_band, y=n))+ 
  geom_bar(stat='identity')+ 
  coord_flip()+theme(axis.text.y=element_blank())


#subset excludes : PROPERTY_TYPE = 'Park home' , n_builtForm = 'unknown'
#it have new variables:
#nn_construction_age_band
#nn_CURRENT_ENERGY_EFFICIENCY
#n_difference_potential

#save(big_Dt_subset, file = "../Outputs/WIP_crossSectional/ONSUD_crossSectional_subset_N16744771_.RData" )  
}
```





